import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr"
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "copy-on-build",
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length === 0) {
            const destinations = [
              path.resolve(process.cwd(), "../StoneGate-plugin")
            ];
            if (process.env.OBSIDIAN_VAULT_PATH) {
              destinations.push(process.env.OBSIDIAN_VAULT_PATH);
            }
            for (const destDir of destinations) {
              if (!fs.existsSync(destDir)) {
                fs.mkdirSync(destDir, { recursive: true });
              }
              try {
                fs.copyFileSync("main.js", path.join(destDir, "main.js"));
                fs.copyFileSync("manifest.json", path.join(destDir, "manifest.json"));
                if (fs.existsSync("styles.css")) {
                  fs.copyFileSync("styles.css", path.join(destDir, "styles.css"));
                }
                console.log(`Successfully copied release files to ${destDir}`);
              } catch (err) {
                console.error(`Failed to copy release files to ${destDir}`, err);
              }
            }
          }
        });
      }
    }
  ]
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
