/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StoneGatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  enabled: false,
  passwordHash: void 0,
  passwordSalt: void 0,
  passwordHint: void 0,
  showMasterHint: false,
  protectedPaths: [
    {
      id: "default",
      path: "/",
      label: "Vault",
      timeoutMinutes: 3,
      showHint: false,
      enableGhostMode: false,
      lastUnlocked: void 0
    }
  ],
  lockOnStartup: true,
  lockOnBlur: false,
  blurGracePeriodSeconds: 3,
  intruderAlert: false,
  maxFailedAttempts: 3,
  lockoutDurationSeconds: 60,
  failedAttempts: 0,
  totalIntruderAttempts: 0,
  lockoutUntil: 0,
  recoveryCodeHash: void 0,
  recoveryCodeSalt: void 0,
  showStoneGateTitle: true,
  customTitle: void 0,
  unlockMenuPasswordHash: void 0,
  unlockMenuPasswordSalt: void 0,
  unlockMenuPasswordHint: void 0,
  customBackgroundUrl: ""
};

// src/lock-manager.ts
var import_obsidian = require("obsidian");
var LockManager = class {
  constructor(app, settings, overlay) {
    // pathId -> timestamp when last unlocked
    this.unlockedPaths = /* @__PURE__ */ new Map();
    this.previousFile = null;
    this.idleTimerId = null;
    this.blurTimerId = null;
    this.lastActivityTime = Date.now();
    this.onStateChangeCallbacks = [];
    this.boundActivityHandler = this.throttleActivity.bind(this);
    this.boundBlurHandler = this.handleWindowBlur.bind(this);
    this.boundFocusHandler = this.handleWindowFocus.bind(this);
    // Used for throttling activity updates (max once per second)
    this.activityUpdatePending = false;
    this.ghostModeObserver = null;
    this.app = app;
    this.settings = settings;
    this.overlay = overlay;
    this.debouncedUpdateGhostMode = (0, import_obsidian.debounce)(this.updateGhostModeDOM.bind(this), 100, true);
    this.setupListeners();
    this.startIdleChecker();
    this.updateGhostModeStyles();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.checkTimeouts();
    this.updateGhostModeStyles();
  }
  setupListeners() {
    activeDocument.addEventListener("mousemove", this.boundActivityHandler);
    activeDocument.addEventListener("keydown", this.boundActivityHandler);
    activeDocument.addEventListener("mousedown", this.boundActivityHandler);
    activeDocument.addEventListener("touchstart", this.boundActivityHandler);
    window.addEventListener("blur", this.boundBlurHandler);
    window.addEventListener("focus", this.boundFocusHandler);
  }
  throttleActivity() {
    if (this.activityUpdatePending)
      return;
    this.activityUpdatePending = true;
    window.setTimeout(() => {
      this.lastActivityTime = Date.now();
      this.activityUpdatePending = false;
    }, 1e3);
  }
  startIdleChecker() {
    const check = () => {
      this.checkTimeouts();
      this.idleTimerId = window.setTimeout(check, 1e4);
    };
    this.idleTimerId = window.setTimeout(check, 1e4);
  }
  checkTimeouts() {
    const now = Date.now();
    let lockOccurred = false;
    for (const path of this.settings.protectedPaths) {
      const idleTimeMinutes = (now - this.lastActivityTime) / 1e3 / 60;
      if (idleTimeMinutes >= path.timeoutMinutes) {
        if (this.unlockedPaths.has(path.id)) {
          this.unlockedPaths.delete(path.id);
          lockOccurred = true;
        }
      }
    }
    if (lockOccurred) {
      this.notifyStateChange(true);
      this.updateGhostModeStyles();
    }
    const currentFile = this.app.workspace.getActiveFile();
    if (currentFile && this.isLocked(currentFile.path)) {
      const matchingPath = this.getMatchingPath(currentFile.path);
      if (matchingPath) {
        const idleTimeMinutes = (now - this.lastActivityTime) / 1e3 / 60;
        if (idleTimeMinutes >= matchingPath.timeoutMinutes) {
          if (!this.overlay.isVisible()) {
            this.triggerLock(currentFile.path);
          }
        }
      }
    }
  }
  getMatchingPath(filePath) {
    let match = null;
    let longestPathLength = -1;
    for (const p of this.settings.protectedPaths) {
      if (p.path === "" || p.path === "/") {
        if (longestPathLength < 0) {
          match = p;
          longestPathLength = 0;
        }
      } else if (filePath === p.path || filePath.startsWith(p.path + "/")) {
        if (p.path.length > longestPathLength) {
          match = p;
          longestPathLength = p.path.length;
        }
      }
    }
    return match;
  }
  getPreviousFile() {
    return this.previousFile;
  }
  setPreviousFile(filePath) {
    this.previousFile = filePath;
  }
  isLocked(filePath) {
    if (!this.settings.enabled)
      return false;
    const matchingPath = this.getMatchingPath(filePath);
    if (!matchingPath)
      return false;
    if (!matchingPath.passwordHash && !this.settings.passwordHash)
      return false;
    return !this.unlockedPaths.has(matchingPath.id);
  }
  triggerLock(filePath) {
    if (!this.settings.enabled)
      return;
    const matchingPath = this.getMatchingPath(filePath);
    if (!matchingPath)
      return;
    if (!matchingPath.passwordHash && !this.settings.passwordHash)
      return;
    if (this.overlay.isVisible())
      return;
    this.overlay.show(matchingPath, this.previousFile, (success) => {
      if (success) {
        this.unlock(matchingPath.id);
      } else {
      }
    });
  }
  unlock(pathId) {
    const now = Date.now();
    this.unlockedPaths.set(pathId, now);
    const pathObj = this.settings.protectedPaths.find((p) => p.id === pathId);
    if (pathObj) {
      pathObj.lastUnlocked = now;
    }
    this.notifyStateChange(false);
    this.updateGhostModeStyles();
  }
  lock(pathId) {
    this.unlockedPaths.delete(pathId);
    this.notifyStateChange(true);
    this.updateGhostModeStyles();
  }
  lockAll() {
    this.unlockedPaths.clear();
    this.notifyStateChange(true);
    this.updateGhostModeStyles();
  }
  onLockStateChange(callback) {
    this.onStateChangeCallbacks.push(callback);
  }
  notifyStateChange(locked) {
    for (const cb of this.onStateChangeCallbacks) {
      cb(locked);
    }
  }
  handleFileOpen(file) {
    if (!file)
      return;
    this.lastActivityTime = Date.now();
    if (this.isLocked(file.path)) {
      this.triggerLock(file.path);
    }
  }
  handleWindowBlur() {
    var _a;
    if (!this.settings.enabled || !this.settings.lockOnBlur)
      return;
    if (this.blurTimerId !== null) {
      window.clearTimeout(this.blurTimerId);
    }
    const gracePeriod = (_a = this.settings.blurGracePeriodSeconds) != null ? _a : 3;
    if (gracePeriod <= 0) {
      this.executeBlurLock();
    } else {
      this.blurTimerId = window.setTimeout(() => {
        this.executeBlurLock();
        this.blurTimerId = null;
      }, gracePeriod * 1e3);
    }
  }
  handleWindowFocus() {
    if (this.blurTimerId !== null) {
      window.clearTimeout(this.blurTimerId);
      this.blurTimerId = null;
    }
  }
  executeBlurLock() {
    this.lockAll();
    const currentFile = this.app.workspace.getActiveFile();
    if (currentFile) {
      this.triggerLock(currentFile.path);
    } else {
      const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
      if (defaultPath && (defaultPath.passwordHash || this.settings.passwordHash)) {
        if (!this.overlay.isVisible()) {
          this.overlay.show(defaultPath, this.previousFile, (success) => {
            if (success) {
              this.unlock(defaultPath.id);
            }
          });
        }
      }
    }
  }
  updateGhostModeStyles() {
    if (!this.settings.enabled) {
      if (this.ghostModeObserver) {
        this.ghostModeObserver.disconnect();
        this.ghostModeObserver = null;
      }
      this.clearGhostModeAttributes();
      return;
    }
    if (!this.ghostModeObserver) {
      this.ghostModeObserver = new MutationObserver(() => {
        this.debouncedUpdateGhostMode();
      });
      this.ghostModeObserver.observe(activeDocument.body, { childList: true, subtree: true });
    }
    this.updateGhostModeDOM();
  }
  clearGhostModeAttributes() {
    const els = activeDocument.querySelectorAll("[data-sg-ghost]");
    els.forEach((el) => el.removeAttribute("data-sg-ghost"));
  }
  updateGhostModeDOM() {
    if (!this.settings.enabled) {
      this.clearGhostModeAttributes();
      return;
    }
    const lockedPaths = /* @__PURE__ */ new Set();
    for (const path of this.settings.protectedPaths) {
      if (path.path === "/" || path.path === "")
        continue;
      if (path.enableGhostMode && this.isLocked(path.path)) {
        lockedPaths.add(path.path);
      }
    }
    const titleElements = activeDocument.querySelectorAll(".nav-folder-title[data-path], .nav-file-title[data-path]");
    titleElements.forEach((titleEl) => {
      const path = titleEl.getAttribute("data-path");
      const parentEl = titleEl.parentElement;
      if (parentEl && path) {
        if (lockedPaths.has(path)) {
          if (parentEl.getAttribute("data-sg-ghost") !== "true") {
            parentEl.setAttribute("data-sg-ghost", "true");
          }
        } else {
          if (parentEl.hasAttribute("data-sg-ghost")) {
            parentEl.removeAttribute("data-sg-ghost");
          }
        }
      }
    });
  }
  dispose() {
    activeDocument.removeEventListener("mousemove", this.boundActivityHandler);
    activeDocument.removeEventListener("keydown", this.boundActivityHandler);
    activeDocument.removeEventListener("mousedown", this.boundActivityHandler);
    activeDocument.removeEventListener("touchstart", this.boundActivityHandler);
    window.removeEventListener("blur", this.boundBlurHandler);
    window.removeEventListener("focus", this.boundFocusHandler);
    if (this.idleTimerId !== null) {
      window.clearTimeout(this.idleTimerId);
    }
    if (this.blurTimerId !== null) {
      window.clearTimeout(this.blurTimerId);
    }
    if (this.ghostModeObserver) {
      this.ghostModeObserver.disconnect();
      this.ghostModeObserver = null;
    }
    this.clearGhostModeAttributes();
  }
};

// src/overlay.ts
var import_obsidian2 = require("obsidian");

// src/crypto.ts
function generateSalt() {
  return window.crypto.getRandomValues(new Uint8Array(16));
}
function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return window.btoa(binary);
}
function base64ToArrayBuffer(base64) {
  const binary_string = window.atob(base64);
  const len = binary_string.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binary_string.charCodeAt(i);
  }
  return bytes.buffer;
}
async function hashPassword(password, saltBytes) {
  const encoder = new TextEncoder();
  const passwordData = encoder.encode(password);
  const keyMaterial = await window.crypto.subtle.importKey(
    "raw",
    passwordData,
    { name: "PBKDF2" },
    false,
    ["deriveBits", "deriveKey"]
  );
  const derivedBits = await window.crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      salt: saltBytes,
      iterations: 2e5,
      hash: "SHA-256"
    },
    keyMaterial,
    256
    // 32 bytes
  );
  return arrayBufferToBase64(derivedBits);
}
async function verifyPassword(guess, storedHashBase64, storedSaltBase64) {
  const saltBytes = new Uint8Array(base64ToArrayBuffer(storedSaltBase64));
  const guessHashBase64 = await hashPassword(guess, saltBytes);
  if (guessHashBase64.length !== storedHashBase64.length) {
    return false;
  }
  let match = true;
  for (let i = 0; i < storedHashBase64.length; i++) {
    if (guessHashBase64[i] !== storedHashBase64[i]) {
      match = false;
    }
  }
  return match;
}
function uint8ArrayToBase64(bytes) {
  return arrayBufferToBase64(bytes.buffer);
}
function generateRecoveryCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const randomValues = new Uint8Array(6);
  window.crypto.getRandomValues(randomValues);
  let code = "";
  for (let i = 0; i < 6; i++) {
    code += chars[randomValues[i] % chars.length];
  }
  return code;
}

// src/overlay.ts
var LockOverlay = class {
  constructor(app, settings, saveSettings) {
    this.containerEl = null;
    this.bgLayerEl = null;
    this.inputEl = null;
    this.submitBtnEl = null;
    this.errorEl = null;
    this.counterEl = null;
    this.lockoutEl = null;
    this.recoveryBypassEl = null;
    this.appNameEl = null;
    this.titleEl = null;
    this.hintEl = null;
    this.currentCallback = null;
    this.currentPath = null;
    this.previousFile = null;
    this.lockoutTimer = null;
    this.boundHandleKeydown = this.handleKeydown.bind(this);
    this.observer = null;
    this.isRecoveryPromptOpen = false;
    this.app = app;
    this.settings = settings;
    this.saveSettings = saveSettings;
    this.createOverlay();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.applyBackgroundStyles();
  }
  resolveBackgroundUrl(url) {
    if (!url)
      return "";
    url = url.trim();
    if (/^(https?:\/\/|data:|app:\/\/)/i.test(url)) {
      return url;
    }
    if (url.startsWith("obsidian://")) {
      try {
        const parsed = new URL(url);
        const filePath = parsed.searchParams.get("file") || parsed.searchParams.get("path");
        if (filePath) {
          const file2 = this.app.metadataCache.getFirstLinkpathDest(decodeURIComponent(filePath), "") || this.app.vault.getAbstractFileByPath(decodeURIComponent(filePath));
          if (file2 && file2 instanceof import_obsidian2.TFile) {
            return this.app.vault.getResourcePath(file2);
          }
        }
      } catch (e) {
      }
    }
    const file = this.app.metadataCache.getFirstLinkpathDest(url, "") || this.app.vault.getAbstractFileByPath(url);
    if (file && file instanceof import_obsidian2.TFile) {
      return this.app.vault.getResourcePath(file);
    }
    const isWindowsAbsolute = /^[a-zA-Z]:[\\/]/i.test(url) || url.startsWith("\\\\");
    const isPosixAbsolute = url.startsWith("/");
    if (isWindowsAbsolute || isPosixAbsolute) {
      let normalizedPath = url.replace(/\\/g, "/");
      if (normalizedPath.startsWith("/")) {
        return `app://local${normalizedPath}`;
      } else {
        return `app://local/${normalizedPath}`;
      }
    }
    return url;
  }
  applyBackgroundStyles() {
    if (!this.containerEl || !this.bgLayerEl)
      return;
    const bgUrlSetting = this.settings.customBackgroundUrl;
    if (!bgUrlSetting) {
      this.bgLayerEl.setCssStyles({
        backgroundImage: "",
        backgroundSize: "",
        backgroundPosition: "",
        filter: "",
        transform: "",
        webkitTransform: ""
      });
      return;
    }
    let resolvedUrl = "";
    try {
      resolvedUrl = this.resolveBackgroundUrl(bgUrlSetting);
    } catch (e) {
      console.warn("StoneGate: Background url resolution threw error:", e);
    }
    console.log("StoneGate: Applying background from:", resolvedUrl);
    if (resolvedUrl) {
      this.bgLayerEl.setCssStyles({
        backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url('${resolvedUrl}')`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        filter: "blur(10px)",
        transform: "scale(1.1)",
        webkitTransform: "scale(1.1)"
      });
    } else {
      this.bgLayerEl.setCssStyles({
        backgroundImage: "",
        backgroundSize: "",
        backgroundPosition: "",
        filter: "",
        transform: "",
        webkitTransform: ""
      });
    }
  }
  createOverlay() {
    this.containerEl = activeDocument.createElement("div");
    this.containerEl.addClass("sg-overlay-container", "sg-overlay-hidden");
    this.bgLayerEl = this.containerEl.createDiv("sg-background-layer");
    const card = this.containerEl.createDiv("sg-overlay-card");
    this.appNameEl = card.createEl("div", { text: "StoneGate", cls: "sg-app-name" });
    this.titleEl = card.createEl("h2", { cls: "sg-title" });
    const inputWrapper = card.createDiv("sg-input-wrapper");
    this.inputEl = inputWrapper.createEl("input", {
      type: "password",
      cls: "sg-input",
      attr: { placeholder: "Enter password" }
    });
    const eyeToggle = inputWrapper.createEl("button", { cls: "sg-eye-toggle" });
    (0, import_obsidian2.setIcon)(eyeToggle, "eye");
    eyeToggle.addEventListener("click", () => {
      if (!this.inputEl)
        return;
      const isPassword = this.inputEl.type === "password";
      this.inputEl.type = isPassword ? "text" : "password";
      if (isPassword) {
        (0, import_obsidian2.setIcon)(eyeToggle, "eye-off");
      } else {
        (0, import_obsidian2.setIcon)(eyeToggle, "eye");
      }
    });
    this.hintEl = card.createDiv("sg-hint");
    this.submitBtnEl = card.createEl("button", {
      text: "Unlock",
      cls: "mod-cta sg-submit-btn"
    });
    this.errorEl = card.createDiv("sg-error");
    this.counterEl = card.createDiv("sg-counter");
    this.lockoutEl = card.createDiv("sg-lockout");
    this.recoveryBypassEl = card.createDiv("sg-recovery-bypass");
    this.recoveryBypassEl.hide();
    const recoveryLink = this.recoveryBypassEl.createEl("a", {
      text: "Use Recovery Code",
      cls: "sg-recovery-link"
    });
    recoveryLink.addEventListener("click", (e) => {
      e.preventDefault();
      this.openRecoveryBypassModal();
    });
    this.submitBtnEl.addEventListener("click", () => {
      void this.submit();
    });
    this.containerEl.addEventListener("keydown", (e) => {
      e.stopPropagation();
    });
    activeDocument.body.appendChild(this.containerEl);
    this.observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === "childList") {
          const removedNodes = Array.from(mutation.removedNodes);
          if (this.containerEl && removedNodes.includes(this.containerEl)) {
            activeDocument.body.appendChild(this.containerEl);
          }
        }
      });
    });
    this.observer.observe(activeDocument.body, { childList: true });
  }
  handleKeydown(e) {
    if (!this.containerEl || this.containerEl.hasClass("sg-overlay-hidden"))
      return;
    const isRecoveryModalOpen = !!activeDocument.querySelector(".sg-recovery-modal-container");
    const recoveryModal = activeDocument.querySelector(".sg-recovery-modal-container");
    const recoveryInput = recoveryModal == null ? void 0 : recoveryModal.querySelector("input");
    const activeEl = activeDocument.activeElement;
    const isFocusOnOurInput = activeEl === this.inputEl || recoveryInput && activeEl === recoveryInput;
    const hasModifier = e.ctrlKey || e.metaKey || e.altKey;
    if (hasModifier) {
      const keyLower = e.key.toLowerCase();
      const isEditingShortcut = ["a", "c", "v", "x", "z", "y"].includes(keyLower);
      if (isFocusOnOurInput && isEditingShortcut) {
        return;
      }
      e.stopPropagation();
      e.preventDefault();
      return;
    }
    if (!isFocusOnOurInput) {
      e.stopPropagation();
      e.preventDefault();
      if (isRecoveryModalOpen && recoveryInput) {
        recoveryInput.focus();
      } else if (this.inputEl) {
        const isLockedOut = this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil;
        if (!isLockedOut) {
          this.inputEl.focus();
        }
      }
      return;
    }
    if (e.key === "Enter") {
      e.stopPropagation();
      e.preventDefault();
      if (isRecoveryModalOpen) {
        return;
      }
      void this.submit();
      return;
    }
    if (e.key === "Escape") {
      e.stopPropagation();
      e.preventDefault();
      return;
    }
  }
  show(path, previousFile, callback) {
    if (!this.containerEl)
      return;
    this.currentPath = path;
    this.previousFile = previousFile;
    this.currentCallback = callback;
    if (this.settings.showStoneGateTitle) {
      this.appNameEl.show();
      this.appNameEl.textContent = this.settings.customTitle || "StoneGate";
    } else {
      this.appNameEl.hide();
    }
    this.titleEl.textContent = `${path.label || path.path || "Vault"}`;
    let hintText = "";
    if (path.showHint && path.passwordHint) {
      hintText = path.passwordHint;
    } else if (!path.passwordHash && this.settings.showMasterHint && this.settings.passwordHint) {
      hintText = this.settings.passwordHint;
    }
    this.hintEl.textContent = hintText;
    this.containerEl.removeClass("sg-overlay-hidden");
    this.containerEl.removeClass("sg-overlay-fade-out");
    this.containerEl.addClass("sg-overlay-fade-in");
    const workspace = activeDocument.body.querySelector(".workspace");
    if (workspace)
      workspace.setCssStyles({ pointerEvents: "none" });
    window.addEventListener("keydown", this.boundHandleKeydown, { capture: true });
    if (this.app.workspace.layoutReady) {
      this.applyBackgroundStyles();
    } else {
      this.app.workspace.onLayoutReady(() => {
        this.applyBackgroundStyles();
      });
    }
    if (this.inputEl) {
      this.inputEl.value = "";
      this.errorEl.textContent = "";
      this.updateLockoutUI();
      if (this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil) {
        this.startLockoutTimer();
      } else {
        window.setTimeout(() => {
          var _a;
          return (_a = this.inputEl) == null ? void 0 : _a.focus();
        }, 50);
      }
    }
  }
  isVisible() {
    return !!this.containerEl && !this.containerEl.hasClass("sg-overlay-hidden");
  }
  hide() {
    if (!this.containerEl)
      return;
    this.containerEl.removeClass("sg-overlay-fade-in");
    this.containerEl.addClass("sg-overlay-fade-out");
    window.setTimeout(() => {
      if (this.containerEl) {
        this.containerEl.addClass("sg-overlay-hidden");
      }
      const workspace = activeDocument.body.querySelector(".workspace");
      if (workspace)
        workspace.setCssStyles({ pointerEvents: "" });
      window.removeEventListener("keydown", this.boundHandleKeydown, { capture: true });
    }, 300);
  }
  async handleSuccessfulUnlock() {
    if (this.settings.intruderAlert && this.settings.totalIntruderAttempts > 0) {
      new import_obsidian2.Notice(
        `\u{1F6A8} Security Alert: ${this.settings.totalIntruderAttempts} failed unlock attempt(s) detected.`,
        1e4
      );
    }
    this.settings.failedAttempts = 0;
    this.settings.totalIntruderAttempts = 0;
    this.settings.lockoutUntil = 0;
    await this.saveSettings();
    this.updateLockoutUI();
    this.hide();
    if (this.currentCallback)
      this.currentCallback(true);
  }
  async submit() {
    var _a, _b;
    const hash = ((_a = this.currentPath) == null ? void 0 : _a.passwordHash) || this.settings.passwordHash;
    const salt = ((_b = this.currentPath) == null ? void 0 : _b.passwordSalt) || this.settings.passwordSalt;
    if (!this.inputEl || !hash || !salt) {
      this.hide();
      if (this.currentCallback)
        this.currentCallback(true);
      return;
    }
    if (this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil) {
      return;
    }
    const guess = this.inputEl.value;
    this.inputEl.value = "";
    let isMatch = await verifyPassword(guess, hash, salt);
    if (!isMatch && this.settings.recoveryCodeHash && this.settings.recoveryCodeSalt) {
      const upperGuess = guess.trim().toUpperCase();
      isMatch = await verifyPassword(upperGuess, this.settings.recoveryCodeHash, this.settings.recoveryCodeSalt);
      if (isMatch) {
        new import_obsidian2.Notice("\u{1F513} Unlocked using Recovery Code (Global Skeleton Key).", 5e3);
      }
    }
    if (isMatch) {
      await this.handleSuccessfulUnlock();
    } else {
      this.settings.failedAttempts++;
      this.settings.totalIntruderAttempts++;
      this.errorEl.textContent = "Incorrect password";
      this.inputEl.classList.remove("sg-shake");
      void this.inputEl.offsetWidth;
      this.inputEl.classList.add("sg-shake");
      if (this.settings.maxFailedAttempts > 0 && this.settings.failedAttempts >= this.settings.maxFailedAttempts) {
        this.settings.lockoutUntil = Date.now() + this.settings.lockoutDurationSeconds * 1e3;
        this.settings.failedAttempts = 0;
        await this.saveSettings();
        this.updateLockoutUI();
        this.startLockoutTimer();
      } else {
        await this.saveSettings();
        this.updateLockoutUI();
      }
    }
  }
  openRecoveryBypassModal() {
    if (this.isRecoveryPromptOpen)
      return;
    if (!this.settings.recoveryCodeHash || !this.settings.recoveryCodeSalt) {
      new import_obsidian2.Notice("No Recovery Code is configured. Set one up in StoneGate settings.", 6e3);
      return;
    }
    this.isRecoveryPromptOpen = true;
    new RecoveryBypassModal(this.app, this.settings, (verified) => {
      void (async () => {
        if (verified) {
          new import_obsidian2.Notice("\u{1F513} Lockout bypassed using Recovery Code.", 5e3);
          await this.handleSuccessfulUnlock();
        }
      })();
    }, () => {
      this.isRecoveryPromptOpen = false;
    }).open();
  }
  updateLockoutUI() {
    const isLockedOut = this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil;
    if (isLockedOut) {
      this.inputEl.disabled = true;
      this.submitBtnEl.disabled = true;
      this.errorEl.textContent = "";
      this.counterEl.textContent = "";
      const secondsLeft = Math.ceil((this.settings.lockoutUntil - Date.now()) / 1e3);
      this.lockoutEl.textContent = `Locked out for ${secondsLeft} seconds`;
      if (this.settings.recoveryCodeHash) {
        this.recoveryBypassEl.show();
      }
    } else {
      if (this.settings.lockoutUntil !== 0) {
        this.settings.lockoutUntil = 0;
        void this.saveSettings().catch((err) => console.error("StoneGate: failed to save lockout settings", err));
      }
      this.inputEl.disabled = false;
      this.submitBtnEl.disabled = false;
      this.lockoutEl.textContent = "";
      this.recoveryBypassEl.hide();
      if (this.settings.maxFailedAttempts > 0 && this.settings.failedAttempts > 0) {
        this.counterEl.textContent = `${this.settings.failedAttempts} / ${this.settings.maxFailedAttempts} attempts`;
      } else {
        this.counterEl.textContent = "";
      }
    }
  }
  startLockoutTimer() {
    if (this.lockoutTimer !== null) {
      window.clearInterval(this.lockoutTimer);
    }
    this.lockoutTimer = window.setInterval(() => {
      if (this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil) {
        this.updateLockoutUI();
      } else {
        window.clearInterval(this.lockoutTimer);
        this.lockoutTimer = null;
        this.updateLockoutUI();
        if (this.inputEl && !this.containerEl.hasClass("sg-overlay-hidden")) {
          this.inputEl.focus();
        }
      }
    }, 1e3);
  }
  dispose() {
    if (this.observer) {
      this.observer.disconnect();
    }
    if (this.lockoutTimer !== null) {
      window.clearInterval(this.lockoutTimer);
    }
    window.removeEventListener("keydown", this.boundHandleKeydown, { capture: true });
    if (this.containerEl && this.containerEl.parentNode) {
      this.containerEl.parentNode.removeChild(this.containerEl);
    }
  }
};
var RecoveryBypassModal = class extends import_obsidian2.Modal {
  constructor(app, settings, onResult, onCloseCallback) {
    super(app);
    this.settings = settings;
    this.onResult = onResult;
    this.onCloseCallback = onCloseCallback;
  }
  onOpen() {
    this.containerEl.addClass("sg-recovery-modal-container");
    this.containerEl.addEventListener("keydown", (e) => {
      e.stopPropagation();
    });
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F511} Emergency Recovery Bypass" });
    contentEl.createEl("p", {
      text: "You are currently locked out. Enter your 6-character Recovery Code to immediately bypass the lockout and unlock.",
      cls: "sg-recovery-desc"
    });
    const inputWrapper = contentEl.createDiv("sg-recovery-input-wrapper");
    const input = inputWrapper.createEl("input", {
      type: "text",
      cls: "sg-recovery-input",
      attr: {
        placeholder: "XXXXXX",
        maxlength: "6",
        autocomplete: "off",
        spellcheck: "false"
      }
    });
    input.addEventListener("input", () => {
      var _a;
      const pos = (_a = input.selectionStart) != null ? _a : input.value.length;
      input.value = input.value.toUpperCase();
      input.setSelectionRange(pos, pos);
    });
    const errorEl = contentEl.createDiv("sg-recovery-error");
    const btnRow = contentEl.createDiv("sg-recovery-btn-row");
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    const unlockBtn = btnRow.createEl("button", { text: "Use Recovery Code", cls: "mod-cta" });
    let submitted = false;
    const attempt = async () => {
      if (submitted)
        return;
      errorEl.textContent = "";
      const code = input.value.trim().toUpperCase();
      if (!code) {
        errorEl.textContent = "Please enter your Recovery Code.";
        return;
      }
      unlockBtn.disabled = true;
      unlockBtn.textContent = "Verifying\u2026";
      const isMatch = await verifyPassword(
        code,
        this.settings.recoveryCodeHash,
        this.settings.recoveryCodeSalt
      );
      if (isMatch) {
        submitted = true;
        this.close();
        this.onResult(true);
      } else {
        unlockBtn.disabled = false;
        unlockBtn.textContent = "Use Recovery Code";
        errorEl.textContent = "Invalid Recovery Code. Please check and try again.";
        input.value = "";
        new import_obsidian2.Notice("\u274C Invalid Recovery Code.", 4e3);
      }
    };
    unlockBtn.addEventListener("click", () => {
      void attempt();
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        e.stopPropagation();
        void attempt();
      }
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
    window.setTimeout(() => input.focus(), 80);
  }
  onClose() {
    this.contentEl.empty();
    if (this.onCloseCallback) {
      this.onCloseCallback();
    }
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var StoneGateSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Core").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Enable StoneGate").setDesc("Turn on lock screen protection").addToggle((toggle) => {
      let isSyncing = false;
      toggle.setValue(this.plugin.settings.enabled).onChange((value) => {
        void (async () => {
          if (isSyncing)
            return;
          try {
            if (value) {
              if (!this.plugin.settings.passwordHash) {
                isSyncing = true;
                toggle.setValue(false);
                isSyncing = false;
                new PasswordModal(this.app, this.plugin, void 0, void 0, "Master Password", (success, hash, salt) => {
                  void (async () => {
                    try {
                      if (success && hash && salt) {
                        this.plugin.settings.passwordHash = hash;
                        this.plugin.settings.passwordSalt = salt;
                        this.plugin.settings.enabled = true;
                        await this.plugin.saveSettings();
                        this.display();
                      } else {
                        isSyncing = true;
                        toggle.setValue(false);
                        isSyncing = false;
                      }
                    } catch (e) {
                      console.error("Password modal callback error:", e);
                    }
                  })();
                }).open();
              } else {
                this.plugin.settings.enabled = true;
                await this.plugin.saveSettings();
              }
            } else {
              isSyncing = true;
              toggle.setValue(true);
              isSyncing = false;
              new ConfirmPasswordModal(this.app, this.plugin, this.plugin.settings.passwordHash, this.plugin.settings.passwordSalt, "Master Password", (success) => {
                void (async () => {
                  try {
                    if (success) {
                      this.plugin.settings.enabled = false;
                      await this.plugin.saveSettings();
                      this.plugin.lockManager.lockAll();
                      this.display();
                    } else {
                      isSyncing = true;
                      toggle.setValue(true);
                      isSyncing = false;
                    }
                  } catch (e) {
                    console.error("Confirm password modal callback error:", e);
                  }
                })();
              }).open();
            }
          } catch (e) {
            console.error("Failed to toggle StoneGate:", e);
            isSyncing = true;
            toggle.setValue(!value);
            isSyncing = false;
          }
        })();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Master Password").setHeading();
    const passwordSetting = new import_obsidian3.Setting(containerEl).setName("Password").setDesc("Used to unlock your vault and folders");
    if (this.plugin.settings.passwordHash) {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Change Password").onClick(() => {
          new PasswordModal(this.app, this.plugin, this.plugin.settings.passwordHash, this.plugin.settings.passwordSalt, "Master Password", (success, hash, salt) => {
            void (async () => {
              if (success && hash && salt) {
                this.plugin.settings.passwordHash = hash;
                this.plugin.settings.passwordSalt = salt;
                await this.plugin.saveSettings();
                this.display();
              }
            })();
          }).open();
        })
      ).addButton((btn) => {
        var _a;
        btn.setButtonText("Remove");
        const dBtn = btn;
        if (typeof dBtn.setDestructive === "function") {
          dBtn.setDestructive();
        } else {
          (_a = dBtn["setWarning"]) == null ? void 0 : _a.call(dBtn);
        }
        btn.onClick(() => {
          new ConfirmPasswordModal(this.app, this.plugin, this.plugin.settings.passwordHash, this.plugin.settings.passwordSalt, "Master Password", (success) => {
            void (async () => {
              if (success) {
                this.plugin.settings.passwordHash = void 0;
                this.plugin.settings.passwordSalt = void 0;
                this.plugin.settings.enabled = false;
                await this.plugin.saveSettings();
                this.display();
              }
            })();
          }).open();
        });
      });
    } else {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Set Password").setCta().onClick(() => {
          new PasswordModal(this.app, this.plugin, void 0, void 0, "Master Password", (success, hash, salt) => {
            void (async () => {
              if (success && hash && salt) {
                this.plugin.settings.passwordHash = hash;
                this.plugin.settings.passwordSalt = salt;
                await this.plugin.saveSettings();
                this.display();
              }
            })();
          }).open();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Protected Paths").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Add Protected Path").setDesc("Select a folder to protect.").addButton(
      (btn) => btn.setButtonText("Add Path").setCta().onClick(() => {
        new AddPathModal(this.app, this.plugin, () => this.display()).open();
      })
    );
    const pathsContainer = containerEl.createDiv();
    for (const path of this.plugin.settings.protectedPaths) {
      new import_obsidian3.Setting(pathsContainer).setName(path.path === "/" || path.path === "" ? "Vault" : path.path).setDesc(`${path.label ? path.label + " | " : ""}${path.timeoutMinutes} min timeout${path.passwordHash ? " | \u{1F511} Has own password" : ""}`).addButton(
        (btn) => btn.setButtonText("Edit").onClick(() => {
          new EditPathModal(this.app, this.plugin, path, () => this.display()).open();
        })
      ).addButton(
        (btn) => btn.setButtonText("Remove").onClick(async () => {
          this.plugin.settings.protectedPaths = this.plugin.settings.protectedPaths.filter((p) => p.id !== path.id);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Behavior").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Lock on Startup").setDesc("Require password immediately when opening Obsidian").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.lockOnStartup).onChange((value) => {
        this.plugin.settings.lockOnStartup = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Lock when Obsidian loses focus").setDesc("Lock immediately when the window loses focus").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.lockOnBlur).onChange((value) => {
        this.plugin.settings.lockOnBlur = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Blur Grace Period (seconds)").setDesc("Time in seconds to wait before locking after focus loss (0 = immediate)").addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.blurGracePeriodSeconds)).onChange((value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.blurGracePeriodSeconds = num;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Max Failed Attempts").setDesc("0 = unlimited").addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.maxFailedAttempts)).onChange((value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.maxFailedAttempts = num;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Lockout Duration (seconds)").addText(
      (text) => text.setPlaceholder("60").setValue(String(this.plugin.settings.lockoutDurationSeconds)).onChange((value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.lockoutDurationSeconds = num;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Intruder Alert").setDesc("Show a notice upon unlocking if there were failed attempts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.intruderAlert).onChange((value) => {
        this.plugin.settings.intruderAlert = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Appearance").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Show StoneGate Title").setDesc("Show the 'StoneGate' app name at the top of the lock screen").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStoneGateTitle).onChange((value) => {
        this.plugin.settings.showStoneGateTitle = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Custom Lock Screen Title").setDesc("Custom text to show at the top of the lock screen (defaults to 'StoneGate')").addText(
      (text) => text.setPlaceholder("StoneGate").setValue(this.plugin.settings.customTitle || "").onChange((value) => {
        this.plugin.settings.customTitle = value.trim() || void 0;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Custom Background URL/Path").setDesc("URL or local path to a custom background image. You can use an external URL (http/https), or a local file from the vault (simply type the file name or use the path in the vault).").addText((text) => {
      text.setPlaceholder("https://example.com/image.jpg").setValue(this.plugin.settings.customBackgroundUrl || "").onChange((value) => {
        this.plugin.settings.customBackgroundUrl = value.trim();
        void this.plugin.saveSettings();
      });
      new ImagePathSuggest(this.app, text.inputEl);
    });
    new import_obsidian3.Setting(containerEl).setName("Ghost Mode & Commands").setHeading();
    const unlockMenuPwdSetting = new import_obsidian3.Setting(containerEl).setName("Unlock Menu Access Password").setDesc("Used to access the command palette list of hidden/locked paths");
    if (this.plugin.settings.unlockMenuPasswordHash) {
      unlockMenuPwdSetting.addButton(
        (btn) => btn.setButtonText("Change Password").onClick(() => {
          new PasswordModal(this.app, this.plugin, this.plugin.settings.unlockMenuPasswordHash, this.plugin.settings.unlockMenuPasswordSalt, "Unlock Menu Password", (success, hash, salt) => {
            void (async () => {
              if (success && hash && salt) {
                this.plugin.settings.unlockMenuPasswordHash = hash;
                this.plugin.settings.unlockMenuPasswordSalt = salt;
                await this.plugin.saveSettings();
                this.display();
              }
            })();
          }).open();
        })
      ).addButton((btn) => {
        var _a;
        btn.setButtonText("Remove");
        const dBtn = btn;
        if (typeof dBtn.setDestructive === "function") {
          dBtn.setDestructive();
        } else {
          (_a = dBtn["setWarning"]) == null ? void 0 : _a.call(dBtn);
        }
        btn.onClick(() => {
          new ConfirmPasswordModal(this.app, this.plugin, this.plugin.settings.unlockMenuPasswordHash, this.plugin.settings.unlockMenuPasswordSalt, "Unlock Menu Password", (success) => {
            void (async () => {
              if (success) {
                this.plugin.settings.unlockMenuPasswordHash = void 0;
                this.plugin.settings.unlockMenuPasswordSalt = void 0;
                await this.plugin.saveSettings();
                this.display();
              }
            })();
          }).open();
        });
      });
    } else {
      unlockMenuPwdSetting.addButton(
        (btn) => btn.setButtonText("Set Password").setCta().onClick(() => {
          new PasswordModal(this.app, this.plugin, void 0, void 0, "Unlock Menu Password", (success, hash, salt) => {
            void (async () => {
              if (success && hash && salt) {
                this.plugin.settings.unlockMenuPasswordHash = hash;
                this.plugin.settings.unlockMenuPasswordSalt = salt;
                await this.plugin.saveSettings();
                this.display();
              }
            })();
          }).open();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Unlock Menu Password Hint").setDesc("Hint shown when the Unlock Menu password is requested").addText(
      (text) => text.setPlaceholder("Hint or custom message...").setValue(this.plugin.settings.unlockMenuPasswordHint || "").onChange((value) => {
        this.plugin.settings.unlockMenuPasswordHint = value.trim() || void 0;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Security").setHeading();
    const recoverySetting = new import_obsidian3.Setting(containerEl).setName("Recovery Code (Global Skeleton Key)").setDesc("A 6-character recovery code that can bypass and unlock any path if you forget your password.");
    if (this.plugin.settings.recoveryCodeHash) {
      recoverySetting.setDesc("A recovery code is configured. You can use it to bypass lock screens. (For security, only the hash is stored; the code cannot be shown again).").addButton((btn) => {
        var _a;
        btn.setButtonText("Remove Recovery Code");
        const dBtn = btn;
        if (typeof dBtn.setDestructive === "function") {
          dBtn.setDestructive();
        } else {
          (_a = dBtn["setWarning"]) == null ? void 0 : _a.call(dBtn);
        }
        btn.onClick(() => {
          new ConfirmPasswordModal(
            this.app,
            this.plugin,
            void 0,
            void 0,
            "Master Password",
            (success) => {
              void (async () => {
                if (success) {
                  this.plugin.settings.recoveryCodeHash = void 0;
                  this.plugin.settings.recoveryCodeSalt = void 0;
                  await this.plugin.saveSettings();
                  this.display();
                  new import_obsidian3.Notice("Recovery Code removed successfully.");
                }
              })();
            }
          ).open();
        });
      });
    } else {
      recoverySetting.addButton(
        (btn) => btn.setButtonText("Generate Recovery Code").setCta().onClick(() => {
          new ConfirmPasswordModal(
            this.app,
            this.plugin,
            void 0,
            void 0,
            "Master Password",
            (success) => {
              void (async () => {
                if (success) {
                  const code = generateRecoveryCode();
                  const saltBytes = generateSalt();
                  const hash = await hashPassword(code.toUpperCase(), saltBytes);
                  this.plugin.settings.recoveryCodeHash = hash;
                  this.plugin.settings.recoveryCodeSalt = uint8ArrayToBase64(saltBytes);
                  await this.plugin.saveSettings();
                  this.display();
                  new RecoveryCodeDisplayModal(this.app, code).open();
                }
              })();
            }
          ).open();
        })
      );
    }
  }
};
function createInputWithEye(container, placeholder) {
  const wrapper = container.createDiv("sg-modal-input-container");
  const input = wrapper.createEl("input", { type: "password", attr: { placeholder } });
  const eyeBtn = wrapper.createEl("button", { cls: "sg-eye-toggle" });
  (0, import_obsidian3.setIcon)(eyeBtn, "eye");
  eyeBtn.addEventListener("click", () => {
    const isPassword = input.type === "password";
    input.type = isPassword ? "text" : "password";
    if (isPassword) {
      (0, import_obsidian3.setIcon)(eyeBtn, "eye-off");
    } else {
      (0, import_obsidian3.setIcon)(eyeBtn, "eye");
    }
  });
  return input;
}
var PasswordModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, targetHash, targetSalt, targetName, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.targetHash = targetHash;
    this.targetSalt = targetSalt;
    this.targetName = targetName;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.targetHash ? `Change ${this.targetName}` : `Set ${this.targetName}` });
    let currentInput;
    if (this.targetHash) {
      currentInput = createInputWithEye(contentEl, "Current Password");
    }
    const newPasswordInput = createInputWithEye(contentEl, "New Password");
    const confirmPasswordInput = createInputWithEye(contentEl, "Confirm Password");
    const errorEl = contentEl.createDiv("sg-error");
    const submitBtn = contentEl.createEl("button", { text: "Save", cls: "mod-cta sg-modal-submit-btn" });
    const submit = async () => {
      errorEl.textContent = "";
      if (currentInput) {
        currentInput.setCssStyles({ borderColor: "" });
      }
      if (currentInput && this.targetHash && this.targetSalt) {
        const isMatch = await verifyPassword(currentInput.value, this.targetHash, this.targetSalt);
        if (!isMatch) {
          errorEl.textContent = "Current password is incorrect.";
          currentInput.setCssStyles({ borderColor: "#e05555" });
          return;
        }
      }
      const p1 = newPasswordInput.value;
      const p2 = confirmPasswordInput.value;
      const asciiRegex = new RegExp("^[" + String.fromCharCode(0) + "-\\u007F]*$");
      if (!p1 || p1.length < 4 || !asciiRegex.test(p1)) {
        errorEl.textContent = "Password must be at least 4 ASCII characters.";
        return;
      }
      if (p1 !== p2) {
        errorEl.textContent = "Passwords do not match.";
        return;
      }
      const salt = generateSalt();
      const hash = await hashPassword(p1, salt);
      this.onSubmit(true, hash, uint8ArrayToBase64(salt));
      this.close();
    };
    submitBtn.addEventListener("click", () => {
      void submit();
    });
    const handleKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void submit();
      }
    };
    newPasswordInput.addEventListener("keydown", handleKey);
    confirmPasswordInput.addEventListener("keydown", handleKey);
    if (currentInput)
      currentInput.addEventListener("keydown", handleKey);
    window.setTimeout(() => {
      if (currentInput)
        currentInput.focus();
      else
        newPasswordInput.focus();
    }, 50);
  }
  onClose() {
    this.contentEl.empty();
    this.onSubmit(false);
  }
};
var ConfirmPasswordModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, targetHash, targetSalt, targetName, onSubmit, hint) {
    super(app);
    this.plugin = plugin;
    this.targetHash = targetHash;
    this.targetSalt = targetSalt;
    this.targetName = targetName;
    this.onSubmit = onSubmit;
    this.hint = hint;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `Confirm ${this.targetName}` });
    contentEl.createEl("p", { text: "Please enter the password to continue." });
    const input = createInputWithEye(contentEl, "Password");
    if (this.hint) {
      const hintEl = contentEl.createDiv("sg-hint");
      hintEl.textContent = this.hint;
    }
    const errorEl = contentEl.createDiv("sg-error");
    const submitBtn = contentEl.createEl("button", { text: "Confirm", cls: "mod-cta sg-modal-submit-btn" });
    const submit = async () => {
      errorEl.textContent = "";
      input.setCssStyles({ borderColor: "" });
      const hash = this.targetHash || this.plugin.settings.passwordHash;
      const salt = this.targetSalt || this.plugin.settings.passwordSalt;
      if (!hash || !salt) {
        this.onSubmit(true);
        this.close();
        return;
      }
      const isMatch = await verifyPassword(input.value, hash, salt);
      if (isMatch) {
        this.onSubmit(true);
        this.close();
      } else {
        errorEl.textContent = "Incorrect password.";
        input.setCssStyles({ borderColor: "#e05555" });
      }
    };
    submitBtn.addEventListener("click", () => {
      void submit();
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void submit();
      }
    });
    window.setTimeout(() => input.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
    this.onSubmit(false);
  }
};
var RecoveryCodeDisplayModal = class extends import_obsidian3.Modal {
  constructor(app, code) {
    super(app);
    this.code = code;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F511} Secure Recovery Code Generated", cls: "sg-modal-title" });
    const desc = contentEl.createEl("p", {
      text: "This recovery code acts as a Global Skeleton Key. It can bypass and unlock any locked folder or the vault itself if you forget your password.",
      cls: "sg-modal-desc"
    });
    desc.addClass("sg-display-desc");
    const warningBox = contentEl.createDiv("sg-warning-box sg-display-warning-box");
    warningBox.createEl("strong", { text: "\u26A0\uFE0F IMPORTANT WARNING:", cls: "sg-display-warning-title" });
    warningBox.createEl("span", {
      text: "Write this code down or save it in a secure password manager. For security reasons, the code is hashed before saving, and it CANNOT be shown or recovered again once you close this window.",
      cls: "sg-display-warning-text"
    });
    const codeContainer = contentEl.createDiv("sg-recovery-code-container sg-display-code-container");
    codeContainer.createEl("div", { text: this.code, cls: "sg-display-code-el" });
    const buttonRow = contentEl.createDiv("sg-button-row sg-display-button-row");
    const copyBtn = buttonRow.createEl("button", { text: "Copy Code", cls: "mod-cta" });
    copyBtn.addEventListener("click", () => {
      void (async () => {
        await navigator.clipboard.writeText(this.code);
        new import_obsidian3.Notice("Recovery code copied to clipboard!");
        copyBtn.setText("Copied!");
        window.setTimeout(() => copyBtn.setText("Copy Code"), 2e3);
      })();
    });
    const closeBtn = buttonRow.createEl("button", { text: "Done / I Saved It" });
    closeBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AddPathModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Add Protected Path" });
    const pathWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    pathWrapper.createEl("label", { text: "Folder path (e.g. Secret/ or / for entire vault)" });
    const pathInput = pathWrapper.createEl("input", { type: "text", attr: { placeholder: "Path..." } });
    const dropdown = pathWrapper.createDiv("sg-autocomplete-dropdown");
    dropdown.hide();
    const folders = this.app.vault.getAllFolders().map((f) => f.path);
    folders.unshift("/");
    const updateDropdown = () => {
      dropdown.empty();
      const query = pathInput.value.toLowerCase();
      const matches = folders.filter((f) => f.toLowerCase().includes(query)).slice(0, 8);
      if (matches.length > 0 && query.length > 0) {
        dropdown.show();
        for (const match of matches) {
          const item = dropdown.createDiv({ cls: "sg-autocomplete-item", text: match === "/" ? "Vault (/)" : match });
          item.addEventListener("click", () => {
            pathInput.value = match;
            dropdown.hide();
          });
        }
      } else {
        dropdown.hide();
      }
    };
    pathInput.addEventListener("input", updateDropdown);
    const labelWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    labelWrapper.createEl("label", { text: "Friendly Label (optional)" });
    const labelInput = labelWrapper.createEl("input", { type: "text", attr: { placeholder: "My Secrets" } });
    const timeoutWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    timeoutWrapper.createEl("label", { text: "Timeout in Minutes (decimals allowed, e.g., 0.5 = 30s)" });
    const timeoutInput = timeoutWrapper.createEl("input", { type: "number", attr: { placeholder: "Minutes (e.g. 0.5 = 30s, 3 = 3min)", step: "any" } });
    timeoutInput.value = "3";
    const hintWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    hintWrapper.createEl("label", { text: "Password Hint (optional)" });
    const hintInput = hintWrapper.createEl("input", { type: "text", attr: { placeholder: "Hint or custom message..." } });
    const toggleWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-flex-row" });
    const showHintToggle = toggleWrapper.createEl("input", { type: "checkbox" });
    const showHintLabel = toggleWrapper.createEl("span", { text: "Show hint on lock screen" });
    showHintLabel.addEventListener("click", () => showHintToggle.click());
    const ghostWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-flex-row" });
    const ghostToggle = ghostWrapper.createEl("input", { type: "checkbox" });
    const ghostLabel = ghostWrapper.createEl("span", { text: "Enable Ghost Mode (Hide this path from File Explorer)" });
    ghostLabel.addEventListener("click", () => ghostToggle.click());
    const menuWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-flex-row" });
    const menuToggle = menuWrapper.createEl("input", { type: "checkbox" });
    const menuLabel = menuWrapper.createEl("span", { text: "Show in Unlock Menu" });
    menuLabel.addEventListener("click", () => {
      if (!menuToggle.disabled) {
        menuToggle.click();
      }
    });
    contentEl.createEl("p", {
      text: "If enabled, this path will be listed in the Unlock Menu. Note: Paths with Ghost Mode enabled are ALWAYS listed.",
      cls: "sg-modal-desc-small"
    });
    ghostToggle.addEventListener("change", () => {
      if (ghostToggle.checked) {
        menuToggle.checked = true;
        menuToggle.disabled = true;
      } else {
        menuToggle.disabled = false;
      }
    });
    let tempHash = void 0;
    let tempSalt = void 0;
    const pwdBtn = contentEl.createEl("button", { text: "Set Password for this path (optional)", cls: "sg-path-password-btn" });
    pwdBtn.addEventListener("click", () => {
      new PasswordModal(this.app, this.plugin, void 0, void 0, "Path Password", (success, hash, salt) => {
        if (success && hash && salt) {
          tempHash = hash;
          tempSalt = salt;
          pwdBtn.textContent = "Path password set \u2713";
        }
      }).open();
    });
    const errorEl = contentEl.createDiv("sg-error");
    const submitBtn = contentEl.createEl("button", { text: "Add", cls: "mod-cta sg-modal-submit-btn" });
    const submit = async () => {
      errorEl.textContent = "";
      const pathVal = pathInput.value.trim();
      const labelVal = labelInput.value.trim();
      const timeoutVal = parseFloat(timeoutInput.value);
      if (!pathVal) {
        errorEl.textContent = "Path cannot be empty.";
        return;
      }
      if (isNaN(timeoutVal) || timeoutVal < 0) {
        errorEl.textContent = "Timeout must be a positive number.";
        return;
      }
      if (this.plugin.settings.protectedPaths.some((p) => p.path === pathVal)) {
        errorEl.textContent = "Path is already protected.";
        return;
      }
      this.plugin.settings.protectedPaths.push({
        id: "path-" + Date.now(),
        path: pathVal,
        label: labelVal || void 0,
        timeoutMinutes: timeoutVal,
        passwordHash: tempHash,
        passwordSalt: tempSalt,
        passwordHint: hintInput.value.trim() || void 0,
        showHint: showHintToggle.checked,
        enableGhostMode: ghostToggle.checked,
        showInUnlockMenu: menuToggle.checked
      });
      await this.plugin.saveSettings();
      this.onSubmit(true);
      this.close();
    };
    submitBtn.addEventListener("click", () => {
      void submit();
    });
    const handleKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void submit();
      }
    };
    pathInput.addEventListener("keydown", handleKey);
    labelInput.addEventListener("keydown", handleKey);
    timeoutInput.addEventListener("keydown", handleKey);
    activeDocument.addEventListener("click", (e) => {
      if (!pathWrapper.contains(e.target)) {
        dropdown.hide();
      }
    });
    window.setTimeout(() => pathInput.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var EditPathModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, pathObj, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.pathObj = pathObj;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Edit Protected Path" });
    contentEl.createEl("p", { text: `Path: ${this.pathObj.path === "/" ? "Vault (/)" : this.pathObj.path}` });
    const labelWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    labelWrapper.createEl("label", { text: "Friendly Label" });
    const labelInput = labelWrapper.createEl("input", { type: "text", attr: { placeholder: "Label" } });
    labelInput.value = this.pathObj.label || "";
    const timeoutWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    timeoutWrapper.createEl("label", { text: "Timeout in Minutes (decimals allowed, e.g., 0.5 = 30s)" });
    const timeoutInput = timeoutWrapper.createEl("input", { type: "number", attr: { placeholder: "Minutes", step: "any" } });
    timeoutInput.value = String(this.pathObj.timeoutMinutes);
    const hintWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-small-margin" });
    hintWrapper.createEl("label", { text: "Password Hint" });
    const hintInput = hintWrapper.createEl("input", { type: "text", attr: { placeholder: "Hint or custom message..." } });
    hintInput.value = this.pathObj.passwordHint || "";
    const toggleWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-flex-row" });
    const showHintToggle = toggleWrapper.createEl("input", { type: "checkbox" });
    showHintToggle.checked = this.pathObj.showHint;
    const showHintLabel = toggleWrapper.createEl("span", { text: "Show hint on lock screen" });
    showHintLabel.addEventListener("click", () => showHintToggle.click());
    const ghostWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-flex-row" });
    const ghostToggle = ghostWrapper.createEl("input", { type: "checkbox" });
    ghostToggle.checked = !!this.pathObj.enableGhostMode;
    const ghostLabel = ghostWrapper.createEl("span", { text: "Enable Ghost Mode (Hide this path from File Explorer)" });
    ghostLabel.addEventListener("click", () => ghostToggle.click());
    const menuWrapper = contentEl.createDiv({ cls: "sg-modal-input-container sg-flex-row" });
    const menuToggle = menuWrapper.createEl("input", { type: "checkbox" });
    menuToggle.checked = !!this.pathObj.showInUnlockMenu;
    const menuLabel = menuWrapper.createEl("span", { text: "Show in Unlock Menu" });
    menuLabel.addEventListener("click", () => {
      if (!menuToggle.disabled) {
        menuToggle.click();
      }
    });
    contentEl.createEl("p", {
      text: "If enabled, this path will be listed in the Unlock Menu. Note: Paths with Ghost Mode enabled are ALWAYS listed.",
      cls: "sg-modal-desc-small"
    });
    if (ghostToggle.checked) {
      menuToggle.checked = true;
      menuToggle.disabled = true;
    }
    ghostToggle.addEventListener("change", () => {
      if (ghostToggle.checked) {
        menuToggle.checked = true;
        menuToggle.disabled = true;
      } else {
        menuToggle.disabled = false;
      }
    });
    const pwdControls = contentEl.createDiv("sg-modal-button-row-left");
    const pwdBtn = pwdControls.createEl("button", { text: this.pathObj.passwordHash ? "Change Path Password" : "Set Path Password" });
    pwdBtn.addEventListener("click", () => {
      new PasswordModal(this.app, this.plugin, this.pathObj.passwordHash, this.pathObj.passwordSalt, "Path Password", (success, hash, salt) => {
        void (async () => {
          if (success && hash && salt) {
            this.pathObj.passwordHash = hash;
            this.pathObj.passwordSalt = salt;
            await this.plugin.saveSettings();
            this.onSubmit(true);
            this.close();
          }
        })();
      }).open();
    });
    if (this.pathObj.passwordHash) {
      const rmPwdBtn = pwdControls.createEl("button", { text: "Remove Path Password", cls: "mod-warning" });
      rmPwdBtn.addEventListener("click", () => {
        new ConfirmPasswordModal(this.app, this.plugin, this.pathObj.passwordHash, this.pathObj.passwordSalt, "Path Password", (success) => {
          void (async () => {
            if (success) {
              this.pathObj.passwordHash = void 0;
              this.pathObj.passwordSalt = void 0;
              await this.plugin.saveSettings();
              this.onSubmit(true);
              this.close();
            }
          })();
        }).open();
      });
    }
    const errorEl = contentEl.createDiv("sg-error");
    const controls = contentEl.createDiv("sg-modal-button-row-right");
    const submitBtn = controls.createEl("button", { text: "Save", cls: "mod-cta" });
    const cancelBtn = controls.createEl("button", { text: "Cancel" });
    const submit = async () => {
      errorEl.textContent = "";
      const labelVal = labelInput.value.trim();
      const timeoutVal = parseFloat(timeoutInput.value);
      if (isNaN(timeoutVal) || timeoutVal < 0) {
        errorEl.textContent = "Timeout must be a positive number.";
        return;
      }
      this.pathObj.label = labelVal || void 0;
      this.pathObj.timeoutMinutes = timeoutVal;
      this.pathObj.passwordHint = hintInput.value.trim() || void 0;
      this.pathObj.showHint = showHintToggle.checked;
      this.pathObj.enableGhostMode = ghostToggle.checked;
      this.pathObj.showInUnlockMenu = menuToggle.checked;
      await this.plugin.saveSettings();
      this.plugin.lockManager.updateGhostModeStyles();
      this.onSubmit(true);
      this.close();
    };
    submitBtn.addEventListener("click", () => {
      void submit();
    });
    cancelBtn.addEventListener("click", () => this.close());
    const handleKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void submit();
      }
    };
    labelInput.addEventListener("keydown", handleKey);
    timeoutInput.addEventListener("keydown", handleKey);
    hintInput.addEventListener("keydown", handleKey);
    window.setTimeout(() => labelInput.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImagePathSuggest = class extends import_obsidian3.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const files = this.app.vault.getFiles();
    const extensions = ["png", "jpg", "jpeg", "gif", "svg", "webp"];
    const lowerQuery = query.toLowerCase();
    return files.filter((file) => {
      const ext = file.extension.toLowerCase();
      const matchesExtension = extensions.includes(ext);
      const matchesQuery = file.path.toLowerCase().contains(lowerQuery);
      return matchesExtension && matchesQuery;
    }).map((file) => file.path);
  }
  renderSuggestion(value, el) {
    el.setText(value);
  }
  selectSuggestion(value, evt) {
    this.setValue(value);
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};

// src/unlock-path-modal.ts
var import_obsidian4 = require("obsidian");
var UnlockPathModal = class extends import_obsidian4.FuzzySuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("Search for a locked path to unlock...");
  }
  getItems() {
    return this.plugin.settings.protectedPaths.filter(
      (p) => this.plugin.lockManager.isLocked(p.path) && (p.enableGhostMode === true || p.showInUnlockMenu === true)
    );
  }
  getItemText(item) {
    return item.label ? `${item.label} (${item.path})` : item.path;
  }
  onChooseItem(item, evt) {
    this.plugin.lockManager.triggerLock(item.path);
  }
};

// src/main.ts
var StoneGatePlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.currentFilePath = null;
  }
  async onload() {
    await this.loadSettings();
    this.overlay = new LockOverlay(this.app, this.settings, async () => {
      await this.saveSettings();
    });
    this.lockManager = new LockManager(this.app, this.settings, this.overlay);
    const isLockedOut = this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil;
    if (isLockedOut) {
      const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
      if (defaultPath) {
        this.lockManager.lockAll();
        this.overlay.show(defaultPath, null, (success) => {
          if (success) {
            this.lockManager.unlock(defaultPath.id);
          }
        });
      }
    } else if (this.settings.enabled && this.settings.lockOnStartup) {
      const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
      if (defaultPath && (defaultPath.passwordHash || this.settings.passwordHash)) {
        this.overlay.show(defaultPath, null, (success) => {
          if (success) {
            this.lockManager.unlock(defaultPath.id);
          }
        });
      }
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        const file = this.app.workspace.getActiveFile();
        const newPath = file ? file.path : null;
        if (this.currentFilePath !== newPath) {
          this.lockManager.setPreviousFile(this.currentFilePath);
        }
        this.lockManager.handleFileOpen(file);
        this.currentFilePath = newPath;
      })
    );
    this.addSettingTab(new StoneGateSettingTab(this.app, this));
    this.addCommand({
      id: "lock-vault",
      name: "Lock vault now",
      callback: () => {
        if (this.settings.enabled) {
          const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
          if (defaultPath && (defaultPath.passwordHash || this.settings.passwordHash)) {
            this.lockManager.lockAll();
            this.overlay.show(defaultPath, this.lockManager.getPreviousFile(), (success) => {
              if (success) {
                this.lockManager.unlock(defaultPath.id);
              }
            });
          }
        }
      }
    });
    this.addCommand({
      id: "lock-folder",
      name: "Lock current folder",
      callback: () => {
        const file = this.app.workspace.getActiveFile();
        if (file && this.settings.enabled) {
          const matchingPath = this.lockManager.getMatchingPath(file.path);
          if (matchingPath && (matchingPath.passwordHash || this.settings.passwordHash)) {
            this.lockManager.lock(matchingPath.id);
            this.lockManager.triggerLock(file.path);
          }
        }
      }
    });
    this.addCommand({
      id: "unlock-path",
      name: "Unlock hidden/locked path",
      callback: () => {
        if (!this.settings.enabled)
          return;
        const openUnlockMenu = () => {
          new UnlockPathModal(this.app, this).open();
        };
        if (this.settings.unlockMenuPasswordHash && this.settings.unlockMenuPasswordSalt) {
          new ConfirmPasswordModal(
            this.app,
            this,
            this.settings.unlockMenuPasswordHash,
            this.settings.unlockMenuPasswordSalt,
            "Unlock Menu",
            (success) => {
              if (success) {
                openUnlockMenu();
              }
            },
            this.settings.unlockMenuPasswordHint
          ).open();
        } else {
          openUnlockMenu();
        }
      }
    });
  }
  onunload() {
    this.overlay.dispose();
    this.lockManager.dispose();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.overlay.updateSettings(this.settings);
    this.lockManager.updateSettings(this.settings);
  }
};
