/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StoneGatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  enabled: false,
  passwordHash: void 0,
  passwordSalt: void 0,
  passwordHint: void 0,
  showMasterHint: false,
  protectedPaths: [
    {
      id: "default",
      path: "/",
      label: "Vault",
      timeoutMinutes: 3,
      showHint: false,
      enableGhostMode: false,
      lastUnlocked: void 0
    }
  ],
  lockOnStartup: true,
  lockOnBlur: false,
  blurGracePeriodSeconds: 3,
  intruderAlert: false,
  maxFailedAttempts: 3,
  lockoutDurationSeconds: 60,
  failedAttempts: 0,
  totalIntruderAttempts: 0,
  lockoutUntil: 0,
  recoveryCodeHash: void 0,
  recoveryCodeSalt: void 0,
  showStoneGateTitle: true,
  customTitle: void 0,
  unlockMenuPasswordHash: void 0,
  unlockMenuPasswordSalt: void 0,
  unlockMenuPasswordHint: void 0,
  customBackgroundUrl: ""
};

// src/lock-manager.ts
var LockManager = class {
  constructor(app, settings, overlay) {
    // pathId -> timestamp when last unlocked
    this.unlockedPaths = /* @__PURE__ */ new Map();
    this.previousFile = null;
    this.idleTimerId = null;
    this.blurTimerId = null;
    this.lastActivityTime = Date.now();
    this.onStateChangeCallbacks = [];
    this.boundActivityHandler = this.throttleActivity.bind(this);
    this.boundBlurHandler = this.handleWindowBlur.bind(this);
    this.boundFocusHandler = this.handleWindowFocus.bind(this);
    // Used for throttling activity updates (max once per second)
    this.activityUpdatePending = false;
    this.app = app;
    this.settings = settings;
    this.overlay = overlay;
    this.setupListeners();
    this.startIdleChecker();
    this.updateGhostModeStyles();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.checkTimeouts();
    this.updateGhostModeStyles();
  }
  setupListeners() {
    document.addEventListener("mousemove", this.boundActivityHandler);
    document.addEventListener("keydown", this.boundActivityHandler);
    document.addEventListener("mousedown", this.boundActivityHandler);
    document.addEventListener("touchstart", this.boundActivityHandler);
    window.addEventListener("blur", this.boundBlurHandler);
    window.addEventListener("focus", this.boundFocusHandler);
  }
  throttleActivity() {
    if (this.activityUpdatePending)
      return;
    this.activityUpdatePending = true;
    setTimeout(() => {
      this.lastActivityTime = Date.now();
      this.activityUpdatePending = false;
    }, 1e3);
  }
  startIdleChecker() {
    const check = () => {
      this.checkTimeouts();
      this.idleTimerId = window.setTimeout(check, 1e4);
    };
    this.idleTimerId = window.setTimeout(check, 1e4);
  }
  checkTimeouts() {
    const now = Date.now();
    let lockOccurred = false;
    for (const path of this.settings.protectedPaths) {
      const idleTimeMinutes = (now - this.lastActivityTime) / 1e3 / 60;
      if (idleTimeMinutes >= path.timeoutMinutes) {
        if (this.unlockedPaths.has(path.id)) {
          this.unlockedPaths.delete(path.id);
          lockOccurred = true;
        }
      }
    }
    if (lockOccurred) {
      this.notifyStateChange(true);
    }
    const currentFile = this.app.workspace.getActiveFile();
    if (currentFile && this.isLocked(currentFile.path)) {
      const matchingPath = this.getMatchingPath(currentFile.path);
      if (matchingPath) {
        const idleTimeMinutes = (now - this.lastActivityTime) / 1e3 / 60;
        if (idleTimeMinutes >= matchingPath.timeoutMinutes) {
          if (!this.overlay.isVisible()) {
            this.triggerLock(currentFile.path);
          }
        }
      }
    }
  }
  getMatchingPath(filePath) {
    let match = null;
    let longestPathLength = -1;
    for (const p of this.settings.protectedPaths) {
      if (p.path === "" || p.path === "/") {
        if (longestPathLength < 0) {
          match = p;
          longestPathLength = 0;
        }
      } else if (filePath === p.path || filePath.startsWith(p.path + "/")) {
        if (p.path.length > longestPathLength) {
          match = p;
          longestPathLength = p.path.length;
        }
      }
    }
    return match;
  }
  getPreviousFile() {
    return this.previousFile;
  }
  setPreviousFile(filePath) {
    this.previousFile = filePath;
  }
  isLocked(filePath) {
    if (!this.settings.enabled)
      return false;
    const matchingPath = this.getMatchingPath(filePath);
    if (!matchingPath)
      return false;
    if (!matchingPath.passwordHash && !this.settings.passwordHash)
      return false;
    return !this.unlockedPaths.has(matchingPath.id);
  }
  triggerLock(filePath) {
    if (!this.settings.enabled)
      return;
    const matchingPath = this.getMatchingPath(filePath);
    if (!matchingPath)
      return;
    if (!matchingPath.passwordHash && !this.settings.passwordHash)
      return;
    if (this.overlay.isVisible())
      return;
    this.overlay.show(matchingPath, this.previousFile, (success) => {
      if (success) {
        this.unlock(matchingPath.id);
      } else {
      }
    });
  }
  unlock(pathId) {
    const now = Date.now();
    this.unlockedPaths.set(pathId, now);
    const pathObj = this.settings.protectedPaths.find((p) => p.id === pathId);
    if (pathObj) {
      pathObj.lastUnlocked = now;
    }
    this.notifyStateChange(false);
    this.updateGhostModeStyles();
  }
  lock(pathId) {
    this.unlockedPaths.delete(pathId);
    this.notifyStateChange(true);
    this.updateGhostModeStyles();
  }
  lockAll() {
    this.unlockedPaths.clear();
    this.notifyStateChange(true);
    this.updateGhostModeStyles();
  }
  onLockStateChange(callback) {
    this.onStateChangeCallbacks.push(callback);
  }
  notifyStateChange(locked) {
    for (const cb of this.onStateChangeCallbacks) {
      cb(locked);
    }
  }
  handleFileOpen(file) {
    if (!file)
      return;
    this.lastActivityTime = Date.now();
    if (this.isLocked(file.path)) {
      this.triggerLock(file.path);
    }
  }
  handleWindowBlur() {
    var _a;
    if (!this.settings.enabled || !this.settings.lockOnBlur)
      return;
    if (this.blurTimerId !== null) {
      window.clearTimeout(this.blurTimerId);
    }
    const gracePeriod = (_a = this.settings.blurGracePeriodSeconds) != null ? _a : 3;
    if (gracePeriod <= 0) {
      this.executeBlurLock();
    } else {
      this.blurTimerId = window.setTimeout(() => {
        this.executeBlurLock();
        this.blurTimerId = null;
      }, gracePeriod * 1e3);
    }
  }
  handleWindowFocus() {
    if (this.blurTimerId !== null) {
      window.clearTimeout(this.blurTimerId);
      this.blurTimerId = null;
    }
  }
  executeBlurLock() {
    this.lockAll();
    const currentFile = this.app.workspace.getActiveFile();
    if (currentFile) {
      this.triggerLock(currentFile.path);
    } else {
      const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
      if (defaultPath && (defaultPath.passwordHash || this.settings.passwordHash)) {
        if (!this.overlay.isVisible()) {
          this.overlay.show(defaultPath, this.previousFile, (success) => {
            if (success) {
              this.unlock(defaultPath.id);
            }
          });
        }
      }
    }
  }
  updateGhostModeStyles() {
    let styleEl = document.getElementById("stonegate-ghost-mode");
    if (!this.settings.enabled) {
      if (styleEl)
        styleEl.remove();
      return;
    }
    let css = "";
    for (const path of this.settings.protectedPaths) {
      if (path.path === "/" || path.path === "")
        continue;
      if (path.enableGhostMode && this.isLocked(path.path)) {
        const safePath = path.path.replace(/"/g, '\\"');
        css += `.nav-folder:has(> .nav-folder-title[data-path="${safePath}"]), .nav-file:has(> .nav-file-title[data-path="${safePath}"]) { display: none !important; }
`;
      }
    }
    if (css) {
      if (!styleEl) {
        styleEl = document.createElement("style");
        styleEl.id = "stonegate-ghost-mode";
        document.head.appendChild(styleEl);
      }
      styleEl.textContent = css;
    } else {
      if (styleEl)
        styleEl.remove();
    }
  }
  dispose() {
    document.removeEventListener("mousemove", this.boundActivityHandler);
    document.removeEventListener("keydown", this.boundActivityHandler);
    document.removeEventListener("mousedown", this.boundActivityHandler);
    document.removeEventListener("touchstart", this.boundActivityHandler);
    window.removeEventListener("blur", this.boundBlurHandler);
    window.removeEventListener("focus", this.boundFocusHandler);
    if (this.idleTimerId !== null) {
      window.clearTimeout(this.idleTimerId);
    }
    if (this.blurTimerId !== null) {
      window.clearTimeout(this.blurTimerId);
    }
    const styleEl = document.getElementById("stonegate-ghost-mode");
    if (styleEl)
      styleEl.remove();
  }
};

// src/overlay.ts
var import_obsidian = require("obsidian");

// src/crypto.ts
function generateSalt() {
  return window.crypto.getRandomValues(new Uint8Array(16));
}
function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return window.btoa(binary);
}
function base64ToArrayBuffer(base64) {
  const binary_string = window.atob(base64);
  const len = binary_string.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binary_string.charCodeAt(i);
  }
  return bytes.buffer;
}
async function hashPassword(password, saltBytes) {
  const encoder = new TextEncoder();
  const passwordData = encoder.encode(password);
  const keyMaterial = await window.crypto.subtle.importKey(
    "raw",
    passwordData,
    { name: "PBKDF2" },
    false,
    ["deriveBits", "deriveKey"]
  );
  const derivedBits = await window.crypto.subtle.deriveBits(
    {
      name: "PBKDF2",
      salt: saltBytes,
      iterations: 2e5,
      hash: "SHA-256"
    },
    keyMaterial,
    256
    // 32 bytes
  );
  return arrayBufferToBase64(derivedBits);
}
async function verifyPassword(guess, storedHashBase64, storedSaltBase64) {
  const saltBytes = new Uint8Array(base64ToArrayBuffer(storedSaltBase64));
  const guessHashBase64 = await hashPassword(guess, saltBytes);
  if (guessHashBase64.length !== storedHashBase64.length) {
    return false;
  }
  let match = true;
  for (let i = 0; i < storedHashBase64.length; i++) {
    if (guessHashBase64[i] !== storedHashBase64[i]) {
      match = false;
    }
  }
  return match;
}
function uint8ArrayToBase64(bytes) {
  return arrayBufferToBase64(bytes.buffer);
}
function generateRecoveryCode() {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const randomValues = new Uint8Array(6);
  window.crypto.getRandomValues(randomValues);
  let code = "";
  for (let i = 0; i < 6; i++) {
    code += chars[randomValues[i] % chars.length];
  }
  return code;
}

// src/overlay.ts
var LockOverlay = class {
  constructor(app, settings, saveSettings) {
    this.containerEl = null;
    this.bgLayerEl = null;
    this.inputEl = null;
    this.submitBtnEl = null;
    this.errorEl = null;
    this.counterEl = null;
    this.lockoutEl = null;
    this.recoveryBypassEl = null;
    this.appNameEl = null;
    this.titleEl = null;
    this.hintEl = null;
    this.currentCallback = null;
    this.currentPath = null;
    this.previousFile = null;
    this.lockoutTimer = null;
    this.boundHandleKeydown = this.handleKeydown.bind(this);
    this.observer = null;
    this.isRecoveryPromptOpen = false;
    this.app = app;
    this.settings = settings;
    this.saveSettings = saveSettings;
    this.createOverlay();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.applyBackgroundStyles();
  }
  resolveBackgroundUrl(url) {
    if (!url)
      return "";
    url = url.trim();
    if (/^(https?:\/\/|data:|app:\/\/)/i.test(url)) {
      return url;
    }
    if (url.startsWith("obsidian://")) {
      try {
        const parsed = new URL(url);
        const filePath = parsed.searchParams.get("file") || parsed.searchParams.get("path");
        if (filePath) {
          const file2 = this.app.metadataCache.getFirstLinkpathDest(decodeURIComponent(filePath), "") || this.app.vault.getAbstractFileByPath(decodeURIComponent(filePath));
          if (file2 && file2 instanceof import_obsidian.TFile) {
            return this.app.vault.getResourcePath(file2);
          }
        }
      } catch (e) {
      }
    }
    const file = this.app.metadataCache.getFirstLinkpathDest(url, "") || this.app.vault.getAbstractFileByPath(url);
    if (file && file instanceof import_obsidian.TFile) {
      return this.app.vault.getResourcePath(file);
    }
    const isWindowsAbsolute = /^[a-zA-Z]:[\\/]/i.test(url) || url.startsWith("\\\\");
    const isPosixAbsolute = url.startsWith("/");
    if (isWindowsAbsolute || isPosixAbsolute) {
      let normalizedPath = url.replace(/\\/g, "/");
      if (normalizedPath.startsWith("/")) {
        return `app://local${normalizedPath}`;
      } else {
        return `app://local/${normalizedPath}`;
      }
    }
    return url;
  }
  applyBackgroundStyles() {
    if (!this.containerEl || !this.bgLayerEl)
      return;
    const bgUrlSetting = this.settings.customBackgroundUrl;
    if (!bgUrlSetting) {
      this.bgLayerEl.style.backgroundImage = "";
      this.bgLayerEl.style.backgroundSize = "";
      this.bgLayerEl.style.backgroundPosition = "";
      this.bgLayerEl.style.filter = "";
      this.bgLayerEl.style.transform = "";
      this.bgLayerEl.style.setProperty("-webkit-transform", "");
      return;
    }
    let resolvedUrl = "";
    try {
      resolvedUrl = this.resolveBackgroundUrl(bgUrlSetting);
    } catch (e) {
      console.warn("StoneGate: Background url resolution threw error:", e);
    }
    console.log("StoneGate: Applying background from:", resolvedUrl);
    if (resolvedUrl) {
      this.bgLayerEl.style.backgroundImage = `linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), url('${resolvedUrl}')`;
      this.bgLayerEl.style.backgroundSize = "cover";
      this.bgLayerEl.style.backgroundPosition = "center";
      this.bgLayerEl.style.filter = "blur(10px)";
      this.bgLayerEl.style.transform = "scale(1.1)";
      this.bgLayerEl.style.setProperty("-webkit-transform", "scale(1.1)");
    } else {
      this.bgLayerEl.style.backgroundImage = "";
      this.bgLayerEl.style.backgroundSize = "";
      this.bgLayerEl.style.backgroundPosition = "";
      this.bgLayerEl.style.filter = "";
      this.bgLayerEl.style.transform = "";
      this.bgLayerEl.style.setProperty("-webkit-transform", "");
    }
  }
  createOverlay() {
    this.containerEl = document.createElement("div");
    this.containerEl.addClass("sg-overlay-container", "sg-overlay-hidden");
    this.bgLayerEl = this.containerEl.createDiv("sg-background-layer");
    const card = this.containerEl.createDiv("sg-overlay-card");
    this.appNameEl = card.createEl("div", { text: "StoneGate", cls: "sg-app-name" });
    this.titleEl = card.createEl("h2", { cls: "sg-title" });
    const inputWrapper = card.createDiv("sg-input-wrapper");
    this.inputEl = inputWrapper.createEl("input", {
      type: "password",
      cls: "sg-input",
      attr: { placeholder: "Enter password" }
    });
    const eyeToggle = inputWrapper.createEl("button", { cls: "sg-eye-toggle" });
    eyeToggle.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>`;
    eyeToggle.addEventListener("click", () => {
      if (!this.inputEl)
        return;
      const isPassword = this.inputEl.type === "password";
      this.inputEl.type = isPassword ? "text" : "password";
      if (isPassword) {
        eyeToggle.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>`;
      } else {
        eyeToggle.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>`;
      }
    });
    this.hintEl = card.createDiv("sg-hint");
    this.submitBtnEl = card.createEl("button", {
      text: "Unlock",
      cls: "mod-cta sg-submit-btn"
    });
    this.errorEl = card.createDiv("sg-error");
    this.counterEl = card.createDiv("sg-counter");
    this.lockoutEl = card.createDiv("sg-lockout");
    this.recoveryBypassEl = card.createDiv("sg-recovery-bypass");
    this.recoveryBypassEl.style.display = "none";
    const recoveryLink = this.recoveryBypassEl.createEl("a", {
      text: "Use Recovery Code",
      cls: "sg-recovery-link"
    });
    recoveryLink.addEventListener("click", (e) => {
      e.preventDefault();
      this.openRecoveryBypassModal();
    });
    this.submitBtnEl.addEventListener("click", () => this.submit());
    this.containerEl.addEventListener("keydown", (e) => {
      e.stopPropagation();
    });
    document.body.appendChild(this.containerEl);
    this.observer = new MutationObserver((mutations) => {
      mutations.forEach((mutation) => {
        if (mutation.type === "childList") {
          const removedNodes = Array.from(mutation.removedNodes);
          if (this.containerEl && removedNodes.includes(this.containerEl)) {
            document.body.appendChild(this.containerEl);
          }
        }
      });
    });
    this.observer.observe(document.body, { childList: true });
  }
  handleKeydown(e) {
    if (!this.containerEl || this.containerEl.hasClass("sg-overlay-hidden"))
      return;
    const recoveryModal = document.querySelector(".sg-recovery-modal-container");
    const recoveryInput = recoveryModal == null ? void 0 : recoveryModal.querySelector("input");
    if (recoveryInput && document.activeElement === recoveryInput) {
      if (e.key !== "Enter") {
        e.stopPropagation();
      }
      return;
    }
    e.stopPropagation();
    if (e.key === "Escape") {
      e.preventDefault();
      return;
    }
    if (e.key === "Enter") {
      e.preventDefault();
      this.submit();
      return;
    }
    const isLockedOut = this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil;
    if (!isLockedOut && this.inputEl && document.activeElement !== this.inputEl) {
      this.inputEl.focus();
    }
  }
  show(path, previousFile, callback) {
    if (!this.containerEl)
      return;
    this.currentPath = path;
    this.previousFile = previousFile;
    this.currentCallback = callback;
    if (this.settings.showStoneGateTitle) {
      this.appNameEl.style.display = "block";
      this.appNameEl.textContent = this.settings.customTitle || "StoneGate";
    } else {
      this.appNameEl.style.display = "none";
    }
    this.titleEl.textContent = `${path.label || path.path || "Vault"}`;
    let hintText = "";
    if (path.showHint && path.passwordHint) {
      hintText = path.passwordHint;
    } else if (!path.passwordHash && this.settings.showMasterHint && this.settings.passwordHint) {
      hintText = this.settings.passwordHint;
    }
    this.hintEl.textContent = hintText;
    this.containerEl.removeClass("sg-overlay-hidden");
    this.containerEl.removeClass("sg-overlay-fade-out");
    this.containerEl.addClass("sg-overlay-fade-in");
    const workspace = document.body.querySelector(".workspace");
    if (workspace)
      workspace.style.pointerEvents = "none";
    document.addEventListener("keydown", this.boundHandleKeydown, true);
    if (this.app.workspace.layoutReady) {
      this.applyBackgroundStyles();
    } else {
      this.app.workspace.onLayoutReady(() => {
        this.applyBackgroundStyles();
      });
    }
    if (this.inputEl) {
      this.inputEl.value = "";
      this.errorEl.textContent = "";
      this.updateLockoutUI();
      if (this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil) {
        this.startLockoutTimer();
      } else {
        setTimeout(() => {
          var _a;
          return (_a = this.inputEl) == null ? void 0 : _a.focus();
        }, 50);
      }
    }
  }
  isVisible() {
    return !!this.containerEl && !this.containerEl.hasClass("sg-overlay-hidden");
  }
  hide() {
    if (!this.containerEl)
      return;
    this.containerEl.removeClass("sg-overlay-fade-in");
    this.containerEl.addClass("sg-overlay-fade-out");
    setTimeout(() => {
      if (this.containerEl) {
        this.containerEl.addClass("sg-overlay-hidden");
      }
      const workspace = document.body.querySelector(".workspace");
      if (workspace)
        workspace.style.pointerEvents = "";
      document.removeEventListener("keydown", this.boundHandleKeydown, true);
    }, 300);
  }
  async handleSuccessfulUnlock() {
    if (this.settings.intruderAlert && this.settings.totalIntruderAttempts > 0) {
      new import_obsidian.Notice(
        `\u{1F6A8} Security Alert: ${this.settings.totalIntruderAttempts} failed unlock attempt(s) detected.`,
        1e4
      );
    }
    this.settings.failedAttempts = 0;
    this.settings.totalIntruderAttempts = 0;
    this.settings.lockoutUntil = 0;
    await this.saveSettings();
    this.updateLockoutUI();
    this.hide();
    if (this.currentCallback)
      this.currentCallback(true);
  }
  async submit() {
    var _a, _b;
    const hash = ((_a = this.currentPath) == null ? void 0 : _a.passwordHash) || this.settings.passwordHash;
    const salt = ((_b = this.currentPath) == null ? void 0 : _b.passwordSalt) || this.settings.passwordSalt;
    if (!this.inputEl || !hash || !salt) {
      this.hide();
      if (this.currentCallback)
        this.currentCallback(true);
      return;
    }
    if (this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil) {
      return;
    }
    const guess = this.inputEl.value;
    this.inputEl.value = "";
    let isMatch = await verifyPassword(guess, hash, salt);
    if (!isMatch && this.settings.recoveryCodeHash && this.settings.recoveryCodeSalt) {
      const upperGuess = guess.trim().toUpperCase();
      isMatch = await verifyPassword(upperGuess, this.settings.recoveryCodeHash, this.settings.recoveryCodeSalt);
      if (isMatch) {
        new import_obsidian.Notice("\u{1F513} Unlocked using Recovery Code (Global Skeleton Key).", 5e3);
      }
    }
    if (isMatch) {
      await this.handleSuccessfulUnlock();
    } else {
      this.settings.failedAttempts++;
      this.settings.totalIntruderAttempts++;
      this.errorEl.textContent = "Incorrect password";
      this.inputEl.classList.remove("sg-shake");
      void this.inputEl.offsetWidth;
      this.inputEl.classList.add("sg-shake");
      if (this.settings.maxFailedAttempts > 0 && this.settings.failedAttempts >= this.settings.maxFailedAttempts) {
        this.settings.lockoutUntil = Date.now() + this.settings.lockoutDurationSeconds * 1e3;
        this.settings.failedAttempts = 0;
        await this.saveSettings();
        this.updateLockoutUI();
        this.startLockoutTimer();
      } else {
        await this.saveSettings();
        this.updateLockoutUI();
      }
    }
  }
  openRecoveryBypassModal() {
    if (this.isRecoveryPromptOpen)
      return;
    if (!this.settings.recoveryCodeHash || !this.settings.recoveryCodeSalt) {
      new import_obsidian.Notice("No Recovery Code is configured. Set one up in StoneGate settings.", 6e3);
      return;
    }
    this.isRecoveryPromptOpen = true;
    new RecoveryBypassModal(this.app, this.settings, async (verified) => {
      if (verified) {
        new import_obsidian.Notice("\u{1F513} Lockout bypassed using Recovery Code.", 5e3);
        await this.handleSuccessfulUnlock();
      }
    }, () => {
      this.isRecoveryPromptOpen = false;
    }).open();
  }
  updateLockoutUI() {
    const isLockedOut = this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil;
    if (isLockedOut) {
      this.inputEl.disabled = true;
      this.submitBtnEl.disabled = true;
      this.errorEl.textContent = "";
      this.counterEl.textContent = "";
      const secondsLeft = Math.ceil((this.settings.lockoutUntil - Date.now()) / 1e3);
      this.lockoutEl.textContent = `Locked out for ${secondsLeft} seconds`;
      if (this.settings.recoveryCodeHash) {
        this.recoveryBypassEl.style.display = "block";
      }
    } else {
      if (this.settings.lockoutUntil !== 0) {
        this.settings.lockoutUntil = 0;
        this.saveSettings().catch((err) => console.error("StoneGate: failed to save lockout settings", err));
      }
      this.inputEl.disabled = false;
      this.submitBtnEl.disabled = false;
      this.lockoutEl.textContent = "";
      this.recoveryBypassEl.style.display = "none";
      if (this.settings.maxFailedAttempts > 0 && this.settings.failedAttempts > 0) {
        this.counterEl.textContent = `${this.settings.failedAttempts} / ${this.settings.maxFailedAttempts} attempts`;
      } else {
        this.counterEl.textContent = "";
      }
    }
  }
  startLockoutTimer() {
    if (this.lockoutTimer !== null) {
      window.clearInterval(this.lockoutTimer);
    }
    this.lockoutTimer = window.setInterval(() => {
      if (this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil) {
        this.updateLockoutUI();
      } else {
        window.clearInterval(this.lockoutTimer);
        this.lockoutTimer = null;
        this.updateLockoutUI();
        if (this.inputEl && !this.containerEl.hasClass("sg-overlay-hidden")) {
          this.inputEl.focus();
        }
      }
    }, 1e3);
  }
  dispose() {
    if (this.observer) {
      this.observer.disconnect();
    }
    if (this.lockoutTimer !== null) {
      window.clearInterval(this.lockoutTimer);
    }
    document.removeEventListener("keydown", this.boundHandleKeydown, true);
    if (this.containerEl && this.containerEl.parentNode) {
      this.containerEl.parentNode.removeChild(this.containerEl);
    }
  }
};
var RecoveryBypassModal = class extends import_obsidian.Modal {
  constructor(app, settings, onResult, onCloseCallback) {
    super(app);
    this.settings = settings;
    this.onResult = onResult;
    this.onCloseCallback = onCloseCallback;
  }
  onOpen() {
    this.containerEl.addClass("sg-recovery-modal-container");
    this.containerEl.addEventListener("keydown", (e) => {
      e.stopPropagation();
    });
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F511} Emergency Recovery Bypass" });
    const desc = contentEl.createEl("p", {
      text: "You are currently locked out. Enter your 6-character Recovery Code to immediately bypass the lockout and unlock."
    });
    desc.style.marginBottom = "16px";
    desc.style.color = "var(--text-muted)";
    desc.style.fontSize = "0.9em";
    const inputWrapper = contentEl.createDiv();
    inputWrapper.style.position = "relative";
    const input = inputWrapper.createEl("input", {
      type: "text",
      attr: {
        placeholder: "XXXXXX",
        maxlength: "6",
        autocomplete: "off",
        spellcheck: "false"
      }
    });
    input.style.width = "100%";
    input.style.textTransform = "uppercase";
    input.style.letterSpacing = "4px";
    input.style.textAlign = "center";
    input.style.fontSize = "1.4em";
    input.style.fontFamily = "monospace";
    input.style.padding = "10px 14px";
    input.style.boxSizing = "border-box";
    input.style.marginBottom = "12px";
    input.addEventListener("input", () => {
      var _a;
      const pos = (_a = input.selectionStart) != null ? _a : input.value.length;
      input.value = input.value.toUpperCase();
      input.setSelectionRange(pos, pos);
    });
    const errorEl = contentEl.createDiv();
    errorEl.style.color = "var(--text-error)";
    errorEl.style.fontSize = "0.85em";
    errorEl.style.marginBottom = "16px";
    errorEl.style.minHeight = "1.2em";
    const btnRow = contentEl.createDiv();
    btnRow.style.display = "flex";
    btnRow.style.gap = "10px";
    btnRow.style.justifyContent = "flex-end";
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    const unlockBtn = btnRow.createEl("button", { text: "Use Recovery Code", cls: "mod-cta" });
    unlockBtn.style.marginTop = "0";
    let submitted = false;
    const attempt = async () => {
      if (submitted)
        return;
      errorEl.textContent = "";
      const code = input.value.trim().toUpperCase();
      if (!code) {
        errorEl.textContent = "Please enter your Recovery Code.";
        return;
      }
      unlockBtn.disabled = true;
      unlockBtn.textContent = "Verifying\u2026";
      const isMatch = await verifyPassword(
        code,
        this.settings.recoveryCodeHash,
        this.settings.recoveryCodeSalt
      );
      if (isMatch) {
        submitted = true;
        this.close();
        this.onResult(true);
      } else {
        unlockBtn.disabled = false;
        unlockBtn.textContent = "Use Recovery Code";
        errorEl.textContent = "Invalid Recovery Code. Please check and try again.";
        input.value = "";
        new import_obsidian.Notice("\u274C Invalid Recovery Code.", 4e3);
      }
    };
    unlockBtn.addEventListener("click", attempt);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        e.stopPropagation();
        attempt();
      }
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
    setTimeout(() => input.focus(), 80);
  }
  onClose() {
    this.contentEl.empty();
    if (this.onCloseCallback) {
      this.onCloseCallback();
    }
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var StoneGateSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "StoneGate Settings" });
    new import_obsidian2.Setting(containerEl).setName("Enable StoneGate").setDesc("Turn on lock screen protection").addToggle((toggle) => {
      let isSyncing = false;
      toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        if (isSyncing)
          return;
        try {
          if (value) {
            if (!this.plugin.settings.passwordHash) {
              isSyncing = true;
              toggle.setValue(false);
              isSyncing = false;
              new PasswordModal(this.app, this.plugin, void 0, void 0, "Master Password", async (success, hash, salt) => {
                try {
                  if (success && hash && salt) {
                    this.plugin.settings.passwordHash = hash;
                    this.plugin.settings.passwordSalt = salt;
                    this.plugin.settings.enabled = true;
                    await this.plugin.saveSettings();
                    this.display();
                  } else {
                    isSyncing = true;
                    toggle.setValue(false);
                    isSyncing = false;
                  }
                } catch (e) {
                  console.error("Password modal callback error:", e);
                }
              }).open();
            } else {
              this.plugin.settings.enabled = true;
              await this.plugin.saveSettings();
            }
          } else {
            isSyncing = true;
            toggle.setValue(true);
            isSyncing = false;
            new ConfirmPasswordModal(this.app, this.plugin, this.plugin.settings.passwordHash, this.plugin.settings.passwordSalt, "Master Password", async (success) => {
              try {
                if (success) {
                  this.plugin.settings.enabled = false;
                  await this.plugin.saveSettings();
                  this.plugin.lockManager.lockAll();
                  this.display();
                } else {
                  isSyncing = true;
                  toggle.setValue(true);
                  isSyncing = false;
                }
              } catch (e) {
                console.error("Confirm password modal callback error:", e);
              }
            }).open();
          }
        } catch (e) {
          console.error("Failed to toggle StoneGate:", e);
          isSyncing = true;
          toggle.setValue(!value);
          isSyncing = false;
        }
      });
    });
    containerEl.createEl("h3", { text: "Master Password" });
    const passwordSetting = new import_obsidian2.Setting(containerEl).setName("Password").setDesc("Used to unlock your vault and folders");
    if (this.plugin.settings.passwordHash) {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Change Password").onClick(() => {
          new PasswordModal(this.app, this.plugin, this.plugin.settings.passwordHash, this.plugin.settings.passwordSalt, "Master Password", async (success, hash, salt) => {
            if (success && hash && salt) {
              this.plugin.settings.passwordHash = hash;
              this.plugin.settings.passwordSalt = salt;
              await this.plugin.saveSettings();
              this.display();
            }
          }).open();
        })
      ).addButton(
        (btn) => btn.setButtonText("Remove").setWarning().onClick(() => {
          new ConfirmPasswordModal(this.app, this.plugin, this.plugin.settings.passwordHash, this.plugin.settings.passwordSalt, "Master Password", async (success) => {
            if (success) {
              this.plugin.settings.passwordHash = void 0;
              this.plugin.settings.passwordSalt = void 0;
              this.plugin.settings.enabled = false;
              await this.plugin.saveSettings();
              this.display();
            }
          }).open();
        })
      );
    } else {
      passwordSetting.addButton(
        (btn) => btn.setButtonText("Set Password").setCta().onClick(() => {
          new PasswordModal(this.app, this.plugin, void 0, void 0, "Master Password", async (success, hash, salt) => {
            if (success && hash && salt) {
              this.plugin.settings.passwordHash = hash;
              this.plugin.settings.passwordSalt = salt;
              await this.plugin.saveSettings();
              this.display();
            }
          }).open();
        })
      );
    }
    containerEl.createEl("h3", { text: "Protected Paths" });
    new import_obsidian2.Setting(containerEl).setName("Add Protected Path").setDesc("Select a folder to protect.").addButton(
      (btn) => btn.setButtonText("Add Path").setCta().onClick(() => {
        new AddPathModal(this.app, this.plugin, () => this.display()).open();
      })
    );
    const pathsContainer = containerEl.createDiv();
    for (const path of this.plugin.settings.protectedPaths) {
      new import_obsidian2.Setting(pathsContainer).setName(path.path === "/" || path.path === "" ? "Vault" : path.path).setDesc(`${path.label ? path.label + " | " : ""}${path.timeoutMinutes} min timeout${path.passwordHash ? " | \u{1F511} Has own password" : ""}`).addButton(
        (btn) => btn.setButtonText("Edit").onClick(() => {
          new EditPathModal(this.app, this.plugin, path, () => this.display()).open();
        })
      ).addButton(
        (btn) => btn.setButtonText("Remove").onClick(async () => {
          this.plugin.settings.protectedPaths = this.plugin.settings.protectedPaths.filter((p) => p.id !== path.id);
          await this.plugin.saveSettings();
          this.display();
        })
      );
    }
    containerEl.createEl("h3", { text: "Behavior" });
    new import_obsidian2.Setting(containerEl).setName("Lock on Startup").setDesc("Require password immediately when opening Obsidian").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.lockOnStartup).onChange(async (value) => {
        this.plugin.settings.lockOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Lock when Obsidian loses focus").setDesc("Lock immediately when the window loses focus").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.lockOnBlur).onChange(async (value) => {
        this.plugin.settings.lockOnBlur = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Blur Grace Period (seconds)").setDesc("Time in seconds to wait before locking after focus loss (0 = immediate)").addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.blurGracePeriodSeconds)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.blurGracePeriodSeconds = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Max Failed Attempts").setDesc("0 = unlimited").addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.maxFailedAttempts)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.maxFailedAttempts = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Lockout Duration (seconds)").addText(
      (text) => text.setPlaceholder("60").setValue(String(this.plugin.settings.lockoutDurationSeconds)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.lockoutDurationSeconds = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Intruder Alert").setDesc("Show a notice upon unlocking if there were failed attempts").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.intruderAlert).onChange(async (value) => {
        this.plugin.settings.intruderAlert = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Appearance" });
    new import_obsidian2.Setting(containerEl).setName("Show StoneGate Title").setDesc("Show the 'StoneGate' app name at the top of the lock screen").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showStoneGateTitle).onChange(async (value) => {
        this.plugin.settings.showStoneGateTitle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Custom Lock Screen Title").setDesc("Custom text to show at the top of the lock screen (defaults to 'StoneGate')").addText(
      (text) => text.setPlaceholder("StoneGate").setValue(this.plugin.settings.customTitle || "").onChange(async (value) => {
        this.plugin.settings.customTitle = value.trim() || void 0;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Custom Background URL/Path").setDesc("URL or local path to a custom background image. You can use an external URL (http/https), or a local file from the vault (simply type the file name or use the path in the vault).").addText((text) => {
      text.setPlaceholder("https://example.com/image.jpg").setValue(this.plugin.settings.customBackgroundUrl || "").onChange(async (value) => {
        this.plugin.settings.customBackgroundUrl = value.trim();
        await this.plugin.saveSettings();
      });
      new ImagePathSuggest(this.app, text.inputEl);
    });
    containerEl.createEl("h3", { text: "Ghost Mode & Commands" });
    const unlockMenuPwdSetting = new import_obsidian2.Setting(containerEl).setName("Unlock Menu Access Password").setDesc("Used to access the command palette list of hidden/locked paths");
    if (this.plugin.settings.unlockMenuPasswordHash) {
      unlockMenuPwdSetting.addButton(
        (btn) => btn.setButtonText("Change Password").onClick(() => {
          new PasswordModal(this.app, this.plugin, this.plugin.settings.unlockMenuPasswordHash, this.plugin.settings.unlockMenuPasswordSalt, "Unlock Menu Password", async (success, hash, salt) => {
            if (success && hash && salt) {
              this.plugin.settings.unlockMenuPasswordHash = hash;
              this.plugin.settings.unlockMenuPasswordSalt = salt;
              await this.plugin.saveSettings();
              this.display();
            }
          }).open();
        })
      ).addButton(
        (btn) => btn.setButtonText("Remove").setWarning().onClick(() => {
          new ConfirmPasswordModal(this.app, this.plugin, this.plugin.settings.unlockMenuPasswordHash, this.plugin.settings.unlockMenuPasswordSalt, "Unlock Menu Password", async (success) => {
            if (success) {
              this.plugin.settings.unlockMenuPasswordHash = void 0;
              this.plugin.settings.unlockMenuPasswordSalt = void 0;
              await this.plugin.saveSettings();
              this.display();
            }
          }).open();
        })
      );
    } else {
      unlockMenuPwdSetting.addButton(
        (btn) => btn.setButtonText("Set Password").setCta().onClick(() => {
          new PasswordModal(this.app, this.plugin, void 0, void 0, "Unlock Menu Password", async (success, hash, salt) => {
            if (success && hash && salt) {
              this.plugin.settings.unlockMenuPasswordHash = hash;
              this.plugin.settings.unlockMenuPasswordSalt = salt;
              await this.plugin.saveSettings();
              this.display();
            }
          }).open();
        })
      );
    }
    new import_obsidian2.Setting(containerEl).setName("Unlock Menu Password Hint").setDesc("Hint shown when the Unlock Menu password is requested").addText(
      (text) => text.setPlaceholder("Hint or custom message...").setValue(this.plugin.settings.unlockMenuPasswordHint || "").onChange(async (value) => {
        this.plugin.settings.unlockMenuPasswordHint = value.trim() || void 0;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Recovery Options" });
    const recoverySetting = new import_obsidian2.Setting(containerEl).setName("Recovery Code (Global Skeleton Key)").setDesc("A 6-character recovery code that can bypass and unlock any path if you forget your password.");
    if (this.plugin.settings.recoveryCodeHash) {
      recoverySetting.setDesc("A recovery code is configured. You can use it to bypass lock screens. (For security, only the hash is stored; the code cannot be shown again).").addButton(
        (btn) => btn.setButtonText("Remove Recovery Code").setWarning().onClick(() => {
          new ConfirmPasswordModal(
            this.app,
            this.plugin,
            void 0,
            void 0,
            "Master Password",
            async (success) => {
              if (success) {
                this.plugin.settings.recoveryCodeHash = void 0;
                this.plugin.settings.recoveryCodeSalt = void 0;
                await this.plugin.saveSettings();
                this.display();
                new import_obsidian2.Notice("Recovery Code removed successfully.");
              }
            }
          ).open();
        })
      );
    } else {
      recoverySetting.addButton(
        (btn) => btn.setButtonText("Generate Recovery Code").setCta().onClick(() => {
          new ConfirmPasswordModal(
            this.app,
            this.plugin,
            void 0,
            void 0,
            "Master Password",
            async (success) => {
              if (success) {
                const code = generateRecoveryCode();
                const saltBytes = generateSalt();
                const hash = await hashPassword(code.toUpperCase(), saltBytes);
                this.plugin.settings.recoveryCodeHash = hash;
                this.plugin.settings.recoveryCodeSalt = uint8ArrayToBase64(saltBytes);
                await this.plugin.saveSettings();
                this.display();
                new RecoveryCodeDisplayModal(this.app, code).open();
              }
            }
          ).open();
        })
      );
    }
  }
};
function createInputWithEye(container, placeholder) {
  const wrapper = container.createDiv("sg-modal-input-container");
  const input = wrapper.createEl("input", { type: "password", attr: { placeholder } });
  const eyeBtn = wrapper.createEl("button", { cls: "sg-eye-toggle" });
  eyeBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>`;
  eyeBtn.addEventListener("click", () => {
    const isPassword = input.type === "password";
    input.type = isPassword ? "text" : "password";
    if (isPassword) {
      eyeBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"></path><line x1="1" y1="1" x2="23" y2="23"></line></svg>`;
    } else {
      eyeBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>`;
    }
  });
  return input;
}
var PasswordModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, targetHash, targetSalt, targetName, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.targetHash = targetHash;
    this.targetSalt = targetSalt;
    this.targetName = targetName;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.targetHash ? `Change ${this.targetName}` : `Set ${this.targetName}` });
    let currentInput;
    if (this.targetHash) {
      currentInput = createInputWithEye(contentEl, "Current Password");
    }
    const newPasswordInput = createInputWithEye(contentEl, "New Password");
    const confirmPasswordInput = createInputWithEye(contentEl, "Confirm Password");
    const errorEl = contentEl.createDiv("sg-error");
    const submitBtn = contentEl.createEl("button", { text: "Save", cls: "mod-cta" });
    submitBtn.style.marginTop = "16px";
    const submit = async () => {
      errorEl.textContent = "";
      if (currentInput && this.targetHash && this.targetSalt) {
        const isMatch = await verifyPassword(currentInput.value, this.targetHash, this.targetSalt);
        if (!isMatch) {
          errorEl.textContent = "Current password is incorrect.";
          currentInput.style.borderColor = "#e05555";
          return;
        }
      }
      const p1 = newPasswordInput.value;
      const p2 = confirmPasswordInput.value;
      if (!p1 || p1.length < 4 || !/^[\x00-\x7F]*$/.test(p1)) {
        errorEl.textContent = "Password must be at least 4 ASCII characters.";
        return;
      }
      if (p1 !== p2) {
        errorEl.textContent = "Passwords do not match.";
        return;
      }
      const salt = generateSalt();
      const hash = await hashPassword(p1, salt);
      this.onSubmit(true, hash, uint8ArrayToBase64(salt));
      this.close();
    };
    submitBtn.addEventListener("click", submit);
    const handleKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submit();
      }
    };
    newPasswordInput.addEventListener("keydown", handleKey);
    confirmPasswordInput.addEventListener("keydown", handleKey);
    if (currentInput)
      currentInput.addEventListener("keydown", handleKey);
    setTimeout(() => {
      if (currentInput)
        currentInput.focus();
      else
        newPasswordInput.focus();
    }, 50);
  }
  onClose() {
    this.contentEl.empty();
    this.onSubmit(false);
  }
};
var ConfirmPasswordModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, targetHash, targetSalt, targetName, onSubmit, hint) {
    super(app);
    this.plugin = plugin;
    this.targetHash = targetHash;
    this.targetSalt = targetSalt;
    this.targetName = targetName;
    this.onSubmit = onSubmit;
    this.hint = hint;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `Confirm ${this.targetName}` });
    contentEl.createEl("p", { text: "Please enter the password to continue." });
    const input = createInputWithEye(contentEl, "Password");
    if (this.hint) {
      const hintEl = contentEl.createDiv("sg-hint");
      hintEl.textContent = this.hint;
    }
    const errorEl = contentEl.createDiv("sg-error");
    const submitBtn = contentEl.createEl("button", { text: "Confirm", cls: "mod-cta" });
    submitBtn.style.marginTop = "16px";
    const submit = async () => {
      errorEl.textContent = "";
      const hash = this.targetHash || this.plugin.settings.passwordHash;
      const salt = this.targetSalt || this.plugin.settings.passwordSalt;
      if (!hash || !salt) {
        this.onSubmit(true);
        this.close();
        return;
      }
      const isMatch = await verifyPassword(input.value, hash, salt);
      if (isMatch) {
        this.onSubmit(true);
        this.close();
      } else {
        errorEl.textContent = "Incorrect password.";
        input.style.borderColor = "#e05555";
      }
    };
    submitBtn.addEventListener("click", submit);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submit();
      }
    });
    setTimeout(() => input.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
    this.onSubmit(false);
  }
};
var RecoveryCodeDisplayModal = class extends import_obsidian2.Modal {
  constructor(app, code) {
    super(app);
    this.code = code;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F511} Secure Recovery Code Generated", cls: "sg-modal-title" });
    const desc = contentEl.createEl("p", {
      text: "This recovery code acts as a Global Skeleton Key. It can bypass and unlock any locked folder or the vault itself if you forget your password.",
      cls: "sg-modal-desc"
    });
    desc.style.marginBottom = "16px";
    const warningBox = contentEl.createDiv("sg-warning-box");
    warningBox.style.border = "1px solid var(--text-error)";
    warningBox.style.backgroundColor = "rgba(255, 0, 0, 0.05)";
    warningBox.style.padding = "12px 16px";
    warningBox.style.borderRadius = "6px";
    warningBox.style.marginBottom = "20px";
    const warningTitle = warningBox.createEl("strong", { text: "\u26A0\uFE0F IMPORTANT WARNING:" });
    warningTitle.style.color = "var(--text-error)";
    warningTitle.style.display = "block";
    warningTitle.style.marginBottom = "6px";
    const warningText = warningBox.createEl("span", {
      text: "Write this code down or save it in a secure password manager. For security reasons, the code is hashed before saving, and it CANNOT be shown or recovered again once you close this window."
    });
    warningText.style.fontSize = "0.9em";
    const codeContainer = contentEl.createDiv("sg-recovery-code-container");
    codeContainer.style.textAlign = "center";
    codeContainer.style.margin = "24px 0";
    codeContainer.style.padding = "16px";
    codeContainer.style.borderRadius = "8px";
    codeContainer.style.backgroundColor = "var(--background-secondary-alt)";
    codeContainer.style.border = "2px dashed var(--interactive-accent)";
    const codeEl = codeContainer.createEl("div", { text: this.code });
    codeEl.style.fontSize = "2.4em";
    codeEl.style.fontWeight = "bold";
    codeEl.style.letterSpacing = "6px";
    codeEl.style.color = "var(--interactive-accent)";
    codeEl.style.fontFamily = "monospace";
    codeEl.style.userSelect = "all";
    const buttonRow = contentEl.createDiv("sg-button-row");
    buttonRow.style.display = "flex";
    buttonRow.style.justifyContent = "space-between";
    buttonRow.style.marginTop = "24px";
    const copyBtn = buttonRow.createEl("button", { text: "Copy Code", cls: "mod-cta" });
    copyBtn.addEventListener("click", async () => {
      await navigator.clipboard.writeText(this.code);
      new import_obsidian2.Notice("Recovery code copied to clipboard!");
      copyBtn.setText("Copied!");
      setTimeout(() => copyBtn.setText("Copy Code"), 2e3);
    });
    const closeBtn = buttonRow.createEl("button", { text: "Done / I Saved It" });
    closeBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AddPathModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Add Protected Path" });
    const pathWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    pathWrapper.createEl("label", { text: "Folder path (e.g. Secret/ or / for entire vault)" }).style.display = "block";
    pathWrapper.style.marginBottom = "8px";
    const pathInput = pathWrapper.createEl("input", { type: "text", attr: { placeholder: "Path..." } });
    pathInput.style.width = "100%";
    const dropdown = pathWrapper.createDiv("sg-autocomplete-dropdown");
    dropdown.style.display = "none";
    const folders = this.app.vault.getAllFolders().map((f) => f.path);
    folders.unshift("/");
    const updateDropdown = () => {
      dropdown.empty();
      const query = pathInput.value.toLowerCase();
      const matches = folders.filter((f) => f.toLowerCase().includes(query)).slice(0, 8);
      if (matches.length > 0 && query.length > 0) {
        dropdown.style.display = "block";
        for (const match of matches) {
          const item = dropdown.createDiv({ cls: "sg-autocomplete-item", text: match === "/" ? "Vault (/)" : match });
          item.addEventListener("click", () => {
            pathInput.value = match;
            dropdown.style.display = "none";
          });
        }
      } else {
        dropdown.style.display = "none";
      }
    };
    pathInput.addEventListener("input", updateDropdown);
    const labelWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    labelWrapper.createEl("label", { text: "Friendly Label (optional)" }).style.display = "block";
    labelWrapper.style.marginBottom = "8px";
    const labelInput = labelWrapper.createEl("input", { type: "text", attr: { placeholder: "My Secrets" } });
    labelInput.style.width = "100%";
    const timeoutWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    timeoutWrapper.createEl("label", { text: "Timeout in Minutes (decimals allowed, e.g., 0.5 = 30s)" }).style.display = "block";
    timeoutWrapper.style.marginBottom = "8px";
    const timeoutInput = timeoutWrapper.createEl("input", { type: "number", attr: { placeholder: "Minutes (e.g. 0.5 = 30s, 3 = 3min)", step: "any" } });
    timeoutInput.style.width = "100%";
    timeoutInput.value = "3";
    const hintWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    hintWrapper.createEl("label", { text: "Password Hint (optional)" }).style.display = "block";
    hintWrapper.style.marginBottom = "8px";
    const hintInput = hintWrapper.createEl("input", { type: "text", attr: { placeholder: "Hint or custom message..." } });
    hintInput.style.width = "100%";
    const toggleWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    toggleWrapper.style.display = "flex";
    toggleWrapper.style.flexDirection = "row";
    toggleWrapper.style.alignItems = "center";
    toggleWrapper.style.justifyContent = "flex-start";
    toggleWrapper.style.gap = "8px";
    toggleWrapper.style.marginBottom = "16px";
    const showHintToggle = toggleWrapper.createEl("input", { type: "checkbox" });
    const showHintLabel = toggleWrapper.createEl("span", { text: "Show hint on lock screen" });
    showHintLabel.style.cursor = "pointer";
    showHintLabel.addEventListener("click", () => showHintToggle.click());
    const ghostWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    ghostWrapper.style.display = "flex";
    ghostWrapper.style.flexDirection = "row";
    ghostWrapper.style.alignItems = "center";
    ghostWrapper.style.justifyContent = "flex-start";
    ghostWrapper.style.gap = "8px";
    ghostWrapper.style.marginBottom = "16px";
    const ghostToggle = ghostWrapper.createEl("input", { type: "checkbox" });
    ghostToggle.style.flexShrink = "0";
    const ghostLabel = ghostWrapper.createEl("span", { text: "Enable Ghost Mode (Hide this path from File Explorer)" });
    ghostLabel.style.cursor = "pointer";
    ghostLabel.addEventListener("click", () => ghostToggle.click());
    const menuWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    menuWrapper.style.display = "flex";
    menuWrapper.style.flexDirection = "row";
    menuWrapper.style.alignItems = "center";
    menuWrapper.style.justifyContent = "flex-start";
    menuWrapper.style.gap = "8px";
    menuWrapper.style.marginBottom = "16px";
    const menuToggle = menuWrapper.createEl("input", { type: "checkbox" });
    menuToggle.style.flexShrink = "0";
    const menuLabel = menuWrapper.createEl("span", { text: "Show in Unlock Menu" });
    menuLabel.style.cursor = "pointer";
    menuLabel.addEventListener("click", () => {
      if (!menuToggle.disabled) {
        menuToggle.click();
      }
    });
    const menuDesc = contentEl.createEl("p", {
      text: "If enabled, this path will be listed in the Unlock Menu. Note: Paths with Ghost Mode enabled are ALWAYS listed."
    });
    menuDesc.style.fontSize = "0.85em";
    menuDesc.style.color = "var(--text-muted)";
    menuDesc.style.marginTop = "-12px";
    menuDesc.style.marginBottom = "16px";
    ghostToggle.addEventListener("change", () => {
      if (ghostToggle.checked) {
        menuToggle.checked = true;
        menuToggle.disabled = true;
      } else {
        menuToggle.disabled = false;
      }
    });
    let tempHash = void 0;
    let tempSalt = void 0;
    const pwdBtn = contentEl.createEl("button", { text: "Set Password for this path (optional)" });
    pwdBtn.style.marginBottom = "16px";
    pwdBtn.addEventListener("click", () => {
      new PasswordModal(this.app, this.plugin, void 0, void 0, "Path Password", (success, hash, salt) => {
        if (success && hash && salt) {
          tempHash = hash;
          tempSalt = salt;
          pwdBtn.textContent = "Path password set \u2713";
        }
      }).open();
    });
    const errorEl = contentEl.createDiv("sg-error");
    const submitBtn = contentEl.createEl("button", { text: "Add", cls: "mod-cta" });
    submitBtn.style.marginTop = "16px";
    const submit = async () => {
      errorEl.textContent = "";
      const pathVal = pathInput.value.trim();
      const labelVal = labelInput.value.trim();
      const timeoutVal = parseFloat(timeoutInput.value);
      if (!pathVal) {
        errorEl.textContent = "Path cannot be empty.";
        return;
      }
      if (isNaN(timeoutVal) || timeoutVal < 0) {
        errorEl.textContent = "Timeout must be a positive number.";
        return;
      }
      if (this.plugin.settings.protectedPaths.some((p) => p.path === pathVal)) {
        errorEl.textContent = "Path is already protected.";
        return;
      }
      this.plugin.settings.protectedPaths.push({
        id: "path-" + Date.now(),
        path: pathVal,
        label: labelVal || void 0,
        timeoutMinutes: timeoutVal,
        passwordHash: tempHash,
        passwordSalt: tempSalt,
        passwordHint: hintInput.value.trim() || void 0,
        showHint: showHintToggle.checked,
        enableGhostMode: ghostToggle.checked,
        showInUnlockMenu: menuToggle.checked
      });
      await this.plugin.saveSettings();
      this.onSubmit(true);
      this.close();
    };
    submitBtn.addEventListener("click", submit);
    const handleKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submit();
      }
    };
    pathInput.addEventListener("keydown", handleKey);
    labelInput.addEventListener("keydown", handleKey);
    timeoutInput.addEventListener("keydown", handleKey);
    document.addEventListener("click", (e) => {
      if (!pathWrapper.contains(e.target)) {
        dropdown.style.display = "none";
      }
    });
    setTimeout(() => pathInput.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var EditPathModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, pathObj, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.pathObj = pathObj;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Edit Protected Path" });
    contentEl.createEl("p", { text: `Path: ${this.pathObj.path === "/" ? "Vault (/)" : this.pathObj.path}` });
    const labelWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    labelWrapper.createEl("label", { text: "Friendly Label" }).style.display = "block";
    labelWrapper.style.marginBottom = "8px";
    const labelInput = labelWrapper.createEl("input", { type: "text", attr: { placeholder: "Label" } });
    labelInput.style.width = "100%";
    labelInput.value = this.pathObj.label || "";
    const timeoutWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    timeoutWrapper.createEl("label", { text: "Timeout in Minutes (decimals allowed, e.g., 0.5 = 30s)" }).style.display = "block";
    timeoutWrapper.style.marginBottom = "8px";
    const timeoutInput = timeoutWrapper.createEl("input", { type: "number", attr: { placeholder: "Minutes", step: "any" } });
    timeoutInput.style.width = "100%";
    timeoutInput.value = String(this.pathObj.timeoutMinutes);
    const hintWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    hintWrapper.createEl("label", { text: "Password Hint" }).style.display = "block";
    hintWrapper.style.marginBottom = "8px";
    const hintInput = hintWrapper.createEl("input", { type: "text", attr: { placeholder: "Hint or custom message..." } });
    hintInput.style.width = "100%";
    hintInput.value = this.pathObj.passwordHint || "";
    const toggleWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    toggleWrapper.style.display = "flex";
    toggleWrapper.style.flexDirection = "row";
    toggleWrapper.style.alignItems = "center";
    toggleWrapper.style.justifyContent = "flex-start";
    toggleWrapper.style.gap = "8px";
    toggleWrapper.style.marginBottom = "16px";
    const showHintToggle = toggleWrapper.createEl("input", { type: "checkbox" });
    showHintToggle.checked = this.pathObj.showHint;
    const showHintLabel = toggleWrapper.createEl("span", { text: "Show hint on lock screen" });
    showHintLabel.style.cursor = "pointer";
    showHintLabel.addEventListener("click", () => showHintToggle.click());
    const ghostWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    ghostWrapper.style.display = "flex";
    ghostWrapper.style.flexDirection = "row";
    ghostWrapper.style.alignItems = "center";
    ghostWrapper.style.justifyContent = "flex-start";
    ghostWrapper.style.gap = "8px";
    ghostWrapper.style.marginBottom = "16px";
    const ghostToggle = ghostWrapper.createEl("input", { type: "checkbox" });
    ghostToggle.style.flexShrink = "0";
    ghostToggle.checked = !!this.pathObj.enableGhostMode;
    const ghostLabel = ghostWrapper.createEl("span", { text: "Enable Ghost Mode (Hide this path from File Explorer)" });
    ghostLabel.style.cursor = "pointer";
    ghostLabel.addEventListener("click", () => ghostToggle.click());
    const menuWrapper = contentEl.createDiv({ cls: "sg-modal-input-container" });
    menuWrapper.style.display = "flex";
    menuWrapper.style.flexDirection = "row";
    menuWrapper.style.alignItems = "center";
    menuWrapper.style.justifyContent = "flex-start";
    menuWrapper.style.gap = "8px";
    menuWrapper.style.marginBottom = "16px";
    const menuToggle = menuWrapper.createEl("input", { type: "checkbox" });
    menuToggle.style.flexShrink = "0";
    menuToggle.checked = !!this.pathObj.showInUnlockMenu;
    const menuLabel = menuWrapper.createEl("span", { text: "Show in Unlock Menu" });
    menuLabel.style.cursor = "pointer";
    menuLabel.addEventListener("click", () => {
      if (!menuToggle.disabled) {
        menuToggle.click();
      }
    });
    const menuDesc = contentEl.createEl("p", {
      text: "If enabled, this path will be listed in the Unlock Menu. Note: Paths with Ghost Mode enabled are ALWAYS listed."
    });
    menuDesc.style.fontSize = "0.85em";
    menuDesc.style.color = "var(--text-muted)";
    menuDesc.style.marginTop = "-12px";
    menuDesc.style.marginBottom = "16px";
    if (ghostToggle.checked) {
      menuToggle.checked = true;
      menuToggle.disabled = true;
    }
    ghostToggle.addEventListener("change", () => {
      if (ghostToggle.checked) {
        menuToggle.checked = true;
        menuToggle.disabled = true;
      } else {
        menuToggle.disabled = false;
      }
    });
    const pwdControls = contentEl.createDiv();
    pwdControls.style.display = "flex";
    pwdControls.style.gap = "8px";
    pwdControls.style.marginBottom = "16px";
    const pwdBtn = pwdControls.createEl("button", { text: this.pathObj.passwordHash ? "Change Path Password" : "Set Path Password" });
    pwdBtn.addEventListener("click", () => {
      new PasswordModal(this.app, this.plugin, this.pathObj.passwordHash, this.pathObj.passwordSalt, "Path Password", async (success, hash, salt) => {
        if (success && hash && salt) {
          this.pathObj.passwordHash = hash;
          this.pathObj.passwordSalt = salt;
          await this.plugin.saveSettings();
          this.onSubmit(true);
          this.close();
        }
      }).open();
    });
    if (this.pathObj.passwordHash) {
      const rmPwdBtn = pwdControls.createEl("button", { text: "Remove Path Password", cls: "mod-warning" });
      rmPwdBtn.addEventListener("click", () => {
        new ConfirmPasswordModal(this.app, this.plugin, this.pathObj.passwordHash, this.pathObj.passwordSalt, "Path Password", async (success) => {
          if (success) {
            this.pathObj.passwordHash = void 0;
            this.pathObj.passwordSalt = void 0;
            await this.plugin.saveSettings();
            this.onSubmit(true);
            this.close();
          }
        }).open();
      });
    }
    const errorEl = contentEl.createDiv("sg-error");
    const controls = contentEl.createDiv();
    controls.style.display = "flex";
    controls.style.gap = "8px";
    controls.style.marginTop = "16px";
    const submitBtn = controls.createEl("button", { text: "Save", cls: "mod-cta" });
    const cancelBtn = controls.createEl("button", { text: "Cancel" });
    const submit = async () => {
      errorEl.textContent = "";
      const labelVal = labelInput.value.trim();
      const timeoutVal = parseFloat(timeoutInput.value);
      if (isNaN(timeoutVal) || timeoutVal < 0) {
        errorEl.textContent = "Timeout must be a positive number.";
        return;
      }
      this.pathObj.label = labelVal || void 0;
      this.pathObj.timeoutMinutes = timeoutVal;
      this.pathObj.passwordHint = hintInput.value.trim() || void 0;
      this.pathObj.showHint = showHintToggle.checked;
      this.pathObj.enableGhostMode = ghostToggle.checked;
      this.pathObj.showInUnlockMenu = menuToggle.checked;
      await this.plugin.saveSettings();
      this.plugin.lockManager.updateGhostModeStyles();
      this.onSubmit(true);
      this.close();
    };
    submitBtn.addEventListener("click", submit);
    cancelBtn.addEventListener("click", () => this.close());
    const handleKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submit();
      }
    };
    labelInput.addEventListener("keydown", handleKey);
    timeoutInput.addEventListener("keydown", handleKey);
    hintInput.addEventListener("keydown", handleKey);
    setTimeout(() => labelInput.focus(), 50);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImagePathSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const files = this.app.vault.getFiles();
    const extensions = ["png", "jpg", "jpeg", "gif", "svg", "webp"];
    const lowerQuery = query.toLowerCase();
    return files.filter((file) => {
      const ext = file.extension.toLowerCase();
      const matchesExtension = extensions.includes(ext);
      const matchesQuery = file.path.toLowerCase().contains(lowerQuery);
      return matchesExtension && matchesQuery;
    }).map((file) => file.path);
  }
  renderSuggestion(value, el) {
    el.setText(value);
  }
  selectSuggestion(value, evt) {
    this.setValue(value);
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};

// src/unlock-path-modal.ts
var import_obsidian3 = require("obsidian");
var UnlockPathModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("Search for a locked path to unlock...");
  }
  getItems() {
    return this.plugin.settings.protectedPaths.filter(
      (p) => this.plugin.lockManager.isLocked(p.path) && (p.enableGhostMode === true || p.showInUnlockMenu === true)
    );
  }
  getItemText(item) {
    return item.label ? `${item.label} (${item.path})` : item.path;
  }
  onChooseItem(item, evt) {
    this.plugin.lockManager.triggerLock(item.path);
  }
};

// src/main.ts
var StoneGatePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.currentFilePath = null;
  }
  async onload() {
    await this.loadSettings();
    this.overlay = new LockOverlay(this.app, this.settings, () => this.saveSettings());
    this.lockManager = new LockManager(this.app, this.settings, this.overlay);
    const isLockedOut = this.settings.lockoutUntil && Date.now() < this.settings.lockoutUntil;
    if (isLockedOut) {
      const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
      if (defaultPath) {
        this.lockManager.lockAll();
        this.overlay.show(defaultPath, null, (success) => {
          if (success) {
            this.lockManager.unlock(defaultPath.id);
          }
        });
      }
    } else if (this.settings.enabled && this.settings.lockOnStartup) {
      const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
      if (defaultPath && (defaultPath.passwordHash || this.settings.passwordHash)) {
        this.overlay.show(defaultPath, null, (success) => {
          if (success) {
            this.lockManager.unlock(defaultPath.id);
          }
        });
      }
    }
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        const file = this.app.workspace.getActiveFile();
        const newPath = file ? file.path : null;
        if (this.currentFilePath !== newPath) {
          this.lockManager.setPreviousFile(this.currentFilePath);
        }
        this.lockManager.handleFileOpen(file);
        this.currentFilePath = newPath;
      })
    );
    this.addSettingTab(new StoneGateSettingTab(this.app, this));
    this.addCommand({
      id: "stonegate-lock-vault",
      name: "Lock vault now",
      callback: () => {
        if (this.settings.enabled) {
          const defaultPath = this.settings.protectedPaths.find((p) => p.id === "default" || p.path === "/");
          if (defaultPath && (defaultPath.passwordHash || this.settings.passwordHash)) {
            this.lockManager.lockAll();
            this.overlay.show(defaultPath, this.lockManager.getPreviousFile(), (success) => {
              if (success) {
                this.lockManager.unlock(defaultPath.id);
              }
            });
          }
        }
      }
    });
    this.addCommand({
      id: "stonegate-lock-folder",
      name: "Lock current folder",
      callback: () => {
        const file = this.app.workspace.getActiveFile();
        if (file && this.settings.enabled) {
          const matchingPath = this.lockManager.getMatchingPath(file.path);
          if (matchingPath && (matchingPath.passwordHash || this.settings.passwordHash)) {
            this.lockManager.lock(matchingPath.id);
            this.lockManager.triggerLock(file.path);
          }
        }
      }
    });
    this.addCommand({
      id: "stonegate-unlock-path",
      name: "Unlock hidden/locked path",
      callback: () => {
        if (!this.settings.enabled)
          return;
        const openUnlockMenu = () => {
          new UnlockPathModal(this.app, this).open();
        };
        if (this.settings.unlockMenuPasswordHash && this.settings.unlockMenuPasswordSalt) {
          new ConfirmPasswordModal(
            this.app,
            this,
            this.settings.unlockMenuPasswordHash,
            this.settings.unlockMenuPasswordSalt,
            "Unlock Menu",
            (success) => {
              if (success) {
                openUnlockMenu();
              }
            },
            this.settings.unlockMenuPasswordHint
          ).open();
        } else {
          openUnlockMenu();
        }
      }
    });
  }
  onunload() {
    this.overlay.dispose();
    this.lockManager.dispose();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.overlay.updateSettings(this.settings);
    this.lockManager.updateSettings(this.settings);
  }
};
